// A slice of Azure's `/cognitiveservices/voices/list`, in the exact shape the endpoint returns.
//
// 🔴 REAL FIELD NAMES AND REAL CASING, INCLUDING THE ONES NEMESIS IGNORES. `SecondaryLocaleList`,
// `RolePlayList`, `WordsPerMinute` and `ExtendedPropertyMap` all arrived after Azure launched this
// endpoint, and a fixture written from the parser rather than from the payload would pass while the
// parser silently dropped everything new. Fields Nemesis does not read are present here on purpose:
// they are what proves the parser tolerates them.
//
// Three languages, chosen to cover what the tests have to prove: English (the default everything is
// accidentally built around), Spanish in two regions (the variety distinction §43 exists for), and
// Japanese (non-Romance, different script, different syllable structure).

export const AZURE_VOICE_LIST: unknown[] = [
  {
    DisplayName: "Jenny",
    Gender: "Female",
    LocalName: "Jenny",
    Locale: "en-US",
    LocaleName: "English (United States)",
    Name: "Microsoft Server Speech Text to Speech Voice (en-US, JennyNeural)",
    SampleRateHertz: "24000",
    ShortName: "en-US-JennyNeural",
    Status: "GA",
    StyleList: ["assistant", "chat", "customerservice", "newscast", "angry", "cheerful", "sad"],
    VoiceType: "Neural",
    WordsPerMinute: "152",
  },
  {
    DisplayName: "Aria",
    Gender: "Female",
    LocalName: "Aria",
    Locale: "en-US",
    LocaleName: "English (United States)",
    Name: "Microsoft Server Speech Text to Speech Voice (en-US, AriaNeural)",
    SampleRateHertz: "24000",
    ShortName: "en-US-AriaNeural",
    Status: "GA",
    StyleList: ["chat", "customerservice", "narration-professional", "newscast-casual"],
    VoiceType: "Neural",
    WordsPerMinute: "150",
  },
  {
    DisplayName: "Guy",
    Gender: "Male",
    LocalName: "Guy",
    Locale: "en-US",
    LocaleName: "English (United States)",
    Name: "Microsoft Server Speech Text to Speech Voice (en-US, GuyNeural)",
    SampleRateHertz: "24000",
    ShortName: "en-US-GuyNeural",
    Status: "GA",
    VoiceType: "Neural",
    WordsPerMinute: "215",
  },
  {
    DisplayName: "Dalia",
    Gender: "Female",
    LocalName: "Dalia",
    Locale: "es-MX",
    LocaleName: "Spanish (Mexico)",
    Name: "Microsoft Server Speech Text to Speech Voice (es-MX, DaliaNeural)",
    RolePlayList: ["Girl", "YoungAdultFemale"],
    SampleRateHertz: "24000",
    ShortName: "es-MX-DaliaNeural",
    Status: "GA",
    StyleList: ["cheerful", "sad", "whispering"],
    VoiceType: "Neural",
    WordsPerMinute: "162",
  },
  {
    DisplayName: "Jorge",
    Gender: "Male",
    LocalName: "Jorge",
    Locale: "es-MX",
    LocaleName: "Spanish (Mexico)",
    Name: "Microsoft Server Speech Text to Speech Voice (es-MX, JorgeNeural)",
    SampleRateHertz: "24000",
    ShortName: "es-MX-JorgeNeural",
    Status: "GA",
    VoiceType: "Neural",
    WordsPerMinute: "160",
  },
  {
    DisplayName: "Elvira",
    Gender: "Female",
    LocalName: "Elvira",
    Locale: "es-ES",
    LocaleName: "Spanish (Spain)",
    Name: "Microsoft Server Speech Text to Speech Voice (es-ES, ElviraNeural)",
    SampleRateHertz: "24000",
    ShortName: "es-ES-ElviraNeural",
    Status: "GA",
    StyleList: ["cheerful", "sad"],
    VoiceType: "Neural",
    WordsPerMinute: "157",
  },
  {
    DisplayName: "Nanami",
    Gender: "Female",
    LocalName: "七海",
    Locale: "ja-JP",
    LocaleName: "Japanese (Japan)",
    Name: "Microsoft Server Speech Text to Speech Voice (ja-JP, NanamiNeural)",
    SampleRateHertz: "24000",
    ShortName: "ja-JP-NanamiNeural",
    Status: "GA",
    StyleList: ["chat", "cheerful", "customerservice"],
    VoiceType: "Neural",
    WordsPerMinute: "220",
  },
  {
    DisplayName: "Keita",
    Gender: "Male",
    LocalName: "圭太",
    Locale: "ja-JP",
    LocaleName: "Japanese (Japan)",
    Name: "Microsoft Server Speech Text to Speech Voice (ja-JP, KeitaNeural)",
    SampleRateHertz: "24000",
    ShortName: "ja-JP-KeitaNeural",
    Status: "GA",
    VoiceType: "Neural",
    WordsPerMinute: "218",
  },
  {
    // A multilingual voice: primary locale en-US, but it lists a dozen others it also speaks. This is
    // how Azure serves a locale that has no dedicated voice of its own.
    DisplayName: "Ava Multilingual",
    Gender: "Female",
    LocalName: "Ava Multilingual",
    Locale: "en-US",
    LocaleName: "English (United States)",
    Name: "Microsoft Server Speech Text to Speech Voice (en-US, AvaMultilingualNeural)",
    SampleRateHertz: "24000",
    SecondaryLocaleList: ["de-DE", "es-ES", "fr-FR", "it-IT", "ja-JP", "pt-BR", "cy-GB"],
    ShortName: "en-US-AvaMultilingualNeural",
    Status: "GA",
    VoiceType: "Neural",
    WordsPerMinute: "150",
  },
  {
    // Preview. Selectable, but never chosen over a GA voice for the same locale.
    DisplayName: "Beatriz",
    Gender: "Female",
    LocalName: "Beatriz",
    Locale: "es-MX",
    LocaleName: "Spanish (Mexico)",
    Name: "Microsoft Server Speech Text to Speech Voice (es-MX, BeatrizNeural)",
    SampleRateHertz: "24000",
    ShortName: "es-MX-BeatrizNeural",
    Status: "Preview",
    VoiceType: "Neural",
    WordsPerMinute: "160",
  },
  {
    // A retired standard voice. Never selected — `selectVoice` filters to neural.
    DisplayName: "Zira",
    Gender: "Female",
    LocalName: "Zira",
    Locale: "en-US",
    LocaleName: "English (United States)",
    Name: "Microsoft Server Speech Text to Speech Voice (en-US, ZiraRUS)",
    SampleRateHertz: "16000",
    ShortName: "en-US-ZiraRUS",
    Status: "GA",
    VoiceType: "Standard",
  },
  {
    // Malformed: no ShortName. Skipped, and counted.
    DisplayName: "Broken",
    Gender: "Female",
    Locale: "en-GB",
    VoiceType: "Neural",
  },
];
