// DEV-ONLY PREVIEW — remove before merge.
// Renders <ResearchPoster> with a realistic health/biomedical fixture so the poster can be
// screenshotted in isolation (no app chrome — this route is a sibling of app/app, whose layout owns
// the rail). The fixture is a plausible finished Deep Research ResearchReport; it is NOT fetched.
import type { Citation, ResearchReport } from "@pharmabro/shared";
import { ResearchPoster } from "@/components/ResearchPoster";

// 30 realistic citations spanning study types + years — a real-sized cited-source list for a
// conference poster. Every findings point below references a chunk_tag that exists here, so the [n]
// markers always resolve to a real reference line.
const CITATIONS: Citation[] = [
  {
    chunk_tag: "S1", source_id: "PMID:15855502", source_type: "pubmed", section: null,
    title: "Metformin and reduced risk of cancer in diabetic patients",
    url: "https://pubmed.ncbi.nlm.nih.gov/15855502/", license: null,
    published_date: "2005-06-04", retrieved_at: "2026-07-04",
    authors: ["Evans JMM", "Donnelly LA", "Emslie-Smith AM", "Alessi DR", "Morris AD"],
    journal: "BMJ", year: "2005", volume: "330", issue: "7503", pages: "1304-1305",
    publication_types: ["Observational Study"],
  },
  {
    chunk_tag: "S2", source_id: "PMID:19934440", source_type: "pubmed", section: null,
    title: "New users of metformin are at low risk of incident cancer: a cohort study",
    url: "https://pubmed.ncbi.nlm.nih.gov/19934440/", license: null,
    published_date: "2009-09-01", retrieved_at: "2026-07-04",
    authors: ["Libby G", "Donnelly LA", "Donnan PT", "Alessi DR", "Morris AD", "Evans JMM"],
    journal: "Diabetes Care", year: "2009", volume: "32", issue: "9", pages: "1620-1625",
    publication_types: ["Observational Study"],
  },
  {
    chunk_tag: "S3", source_id: "PMID:22570464", source_type: "pubmed", section: null,
    title: "Metformin and cancer risk in diabetic patients: a systematic review and meta-analysis",
    url: "https://pubmed.ncbi.nlm.nih.gov/22570464/", license: null,
    published_date: "2012-05-01", retrieved_at: "2026-07-04",
    authors: ["Noto H", "Goto A", "Tsujimoto T", "Noda M"],
    journal: "Cancer Prev Res", year: "2012", volume: "5", issue: "9", pages: "1097-1106",
    publication_types: ["Meta-Analysis", "Systematic Review"], doaj_vetted: true,
  },
  {
    chunk_tag: "S4", source_id: "PMID:24009194", source_type: "pubmed", section: null,
    title: "Metformin and cancer: an ambiguous relationship due to methodological limitations",
    url: "https://pubmed.ncbi.nlm.nih.gov/24009194/", license: null,
    published_date: "2013-09-01", retrieved_at: "2026-07-04",
    authors: ["Suissa S", "Azoulay L"],
    journal: "Diabetes Care", year: "2013", volume: "36", issue: "9", pages: "2665-2673",
    publication_types: ["Review"],
  },
  {
    chunk_tag: "S5", source_id: "PMID:22374499", source_type: "pubmed", section: null,
    title: "Time-related biases in pharmacoepidemiology: immortal time bias and metformin",
    url: "https://pubmed.ncbi.nlm.nih.gov/22374499/", license: null,
    published_date: "2012-02-28", retrieved_at: "2026-07-04",
    authors: ["Suissa S", "Azoulay L"],
    journal: "Diabetes Care", year: "2012", volume: "35", issue: "12", pages: "2665-2673",
    publication_types: ["Journal Article"],
  },
  {
    chunk_tag: "S6", source_id: "PMID:28776081", source_type: "pubmed", section: null,
    title: "Metformin and cancer incidence: an updated meta-analysis of randomized controlled trials",
    url: "https://pubmed.ncbi.nlm.nih.gov/28776081/", license: null,
    published_date: "2017-08-01", retrieved_at: "2026-07-04",
    authors: ["Stevens RJ", "Ali R", "Bankhead CR", "Bethel MA", "Cairns BJ", "Camisasca RP", "Crowe FL", "Farmer AJ", "Harrison S", "Hirst JA"],
    journal: "Diabetologia", year: "2017", volume: "60", issue: "9", pages: "1639-1651",
    publication_types: ["Meta-Analysis"], doaj_vetted: true,
  },
  {
    chunk_tag: "S7", source_id: "NCT01101438", source_type: "clinicaltrials", section: null,
    title: "Metformin in Reducing Cancer Risk in Adults With Type 2 Diabetes",
    url: "https://clinicaltrials.gov/study/NCT01101438", license: null,
    published_date: "2010-04-12", retrieved_at: "2026-07-04",
    year: "2010", study_type: "INTERVENTIONAL", trial_phase: "PHASE3",
  },
  {
    chunk_tag: "S8", source_id: "PMID:33549290", source_type: "pubmed_oa", section: null,
    title: "Metformin use and colorectal cancer risk in type 2 diabetes: a nationwide cohort study",
    url: "https://pubmed.ncbi.nlm.nih.gov/33549290/", license: "cc-by",
    published_date: "2021-02-05", retrieved_at: "2026-07-04",
    authors: ["Kim YJ", "Lee J", "Park S", "Choi KH"],
    journal: "BMC Cancer", year: "2021", volume: "21", issue: "1", pages: "144",
    publication_types: ["Observational Study"], doaj_vetted: true, oa_url: "https://bmccancer.biomedcentral.com/articles/10.1186/s12885-021-07863-z",
  },
  {
    chunk_tag: "S9", source_id: "PMID:29459239", source_type: "pubmed", section: null,
    title: "Confounding by indication and metformin's apparent anticancer effect",
    url: "https://pubmed.ncbi.nlm.nih.gov/29459239/", license: null,
    published_date: "2018-02-01", retrieved_at: "2026-07-04",
    authors: ["Farmer RE", "Ford D", "Forbes HJ", "Chaturvedi N", "Kaplan R", "Smeeth L", "Bhaskaran K"],
    journal: "Int J Epidemiol", year: "2018", volume: "46", issue: "2", pages: "728-744",
    publication_types: ["Observational Study"],
  },
  {
    chunk_tag: "S10", source_id: "PMID:32188585", source_type: "europepmc", section: null,
    title: "Metformin and pancreatic cancer risk: a meta-analysis of observational studies",
    url: "https://europepmc.org/article/MED/32188585", license: null,
    published_date: "2020-03-18", retrieved_at: "2026-07-04",
    authors: ["Zhang H", "Wang Q", "Liu M", "Chen Y"],
    journal: "Pancreas", year: "2020", volume: "49", issue: "4", pages: "504-512",
    publication_types: ["Meta-Analysis"],
  },
  {
    chunk_tag: "S11", source_id: "NCT02614339", source_type: "clinicaltrials", section: null,
    title: "Metformin for Cancer Prevention in Lynch Syndrome (MILY)",
    url: "https://clinicaltrials.gov/study/NCT02614339", license: null,
    published_date: "2015-11-25", retrieved_at: "2026-07-04",
    year: "2015", study_type: "INTERVENTIONAL", trial_phase: "PHASE2",
  },
  {
    chunk_tag: "S12", source_id: "PMID:35435916", source_type: "pubmed", section: null,
    title: "Metformin and overall cancer incidence: umbrella review of meta-analyses",
    url: "https://pubmed.ncbi.nlm.nih.gov/35435916/", license: null,
    published_date: "2022-04-18", retrieved_at: "2026-07-04",
    authors: ["Yao L", "Liu M", "Huang Y", "Wu K", "Zhang X", "Meng H", "Liu R", "Li X", "Yang H"],
    journal: "Diabetes Metab Res Rev", year: "2022", volume: "38", issue: "5", pages: "e3532",
    publication_types: ["Systematic Review"], doaj_vetted: true,
  },
  {
    chunk_tag: "S13", source_id: "PMID:20587581", source_type: "pubmed", section: null,
    title: "Long-term metformin use and the incidence of cancer in patients with type 2 diabetes",
    url: "https://pubmed.ncbi.nlm.nih.gov/20587581/", license: null,
    published_date: "2010-06-29", retrieved_at: "2026-07-04",
    authors: ["Currie CJ", "Poole CD", "Gale EAM"],
    journal: "Diabetologia", year: "2010", volume: "52", issue: "9", pages: "1766-1777",
    publication_types: ["Observational Study"],
  },
  {
    chunk_tag: "S14", source_id: "PMID:23800576", source_type: "pubmed", section: null,
    title: "Metformin and the risk of cancer: a meta-analysis of randomized and observational studies",
    url: "https://pubmed.ncbi.nlm.nih.gov/23800576/", license: null,
    published_date: "2013-06-25", retrieved_at: "2026-07-04",
    authors: ["Gandini S", "Puntoni M", "Heckman-Stoddard BM", "Dunn BK", "Ford L", "DeCensi A", "Szabo E"],
    journal: "Cancer Prev Res", year: "2014", volume: "7", issue: "9", pages: "867-885",
    publication_types: ["Meta-Analysis"], doaj_vetted: true,
  },
  {
    chunk_tag: "S15", source_id: "PMID:26289360", source_type: "pubmed", section: null,
    title: "Metformin therapy and cancer risk: methodological caveats in observational studies",
    url: "https://pubmed.ncbi.nlm.nih.gov/26289360/", license: null,
    published_date: "2015-08-19", retrieved_at: "2026-07-04",
    authors: ["Suissa S"],
    journal: "Diabetologia", year: "2015", volume: "58", issue: "11", pages: "2455-2464",
    publication_types: ["Review"],
  },
  {
    chunk_tag: "S16", source_id: "PMID:31462532", source_type: "pubmed_oa", section: null,
    title: "Metformin and breast cancer incidence in women with type 2 diabetes: a cohort study",
    url: "https://pubmed.ncbi.nlm.nih.gov/31462532/", license: "cc-by",
    published_date: "2019-08-28", retrieved_at: "2026-07-04",
    authors: ["Park YM", "Bookwalter DB", "O'Brien KM", "Jackson CL", "Weinberg CR", "Sandler DP"],
    journal: "Br J Cancer", year: "2019", volume: "121", issue: "7", pages: "623-630",
    publication_types: ["Observational Study"], doaj_vetted: true, oa_url: "https://www.nature.com/articles/s41416-019-0577-4",
  },
  {
    chunk_tag: "S17", source_id: "NCT01864096", source_type: "clinicaltrials", section: null,
    title: "Metformin in Early Breast Cancer (MA.32): a Phase III Adjuvant Trial",
    url: "https://clinicaltrials.gov/study/NCT01864096", license: null,
    published_date: "2013-05-30", retrieved_at: "2026-07-04",
    year: "2013", study_type: "INTERVENTIONAL", trial_phase: "PHASE3",
  },
  {
    chunk_tag: "S18", source_id: "PMID:35168620", source_type: "pubmed", section: null,
    title: "Effect of metformin vs placebo on invasive disease-free survival in early breast cancer (MA.32)",
    url: "https://pubmed.ncbi.nlm.nih.gov/35168620/", license: null,
    published_date: "2022-05-24", retrieved_at: "2026-07-04",
    authors: ["Goodwin PJ", "Chen BE", "Gelmon KA", "Whelan TJ", "Ennis M", "Lemieux J", "Ligibel JA", "Hershman DL", "Mayer IA", "Hobday TJ"],
    journal: "JAMA", year: "2022", volume: "327", issue: "20", pages: "1963-1973",
    publication_types: ["Randomized Controlled Trial"], doaj_vetted: true,
  },
  {
    chunk_tag: "S19", source_id: "PMID:27974556", source_type: "pubmed", section: null,
    title: "Metformin and lung cancer risk in patients with type 2 diabetes mellitus: a meta-analysis",
    url: "https://pubmed.ncbi.nlm.nih.gov/27974556/", license: null,
    published_date: "2016-12-14", retrieved_at: "2026-07-04",
    authors: ["Zhu N", "Zhang Y", "Gong YI", "He J", "Chen X"],
    journal: "Oncotarget", year: "2017", volume: "8", issue: "6", pages: "10233-10240",
    publication_types: ["Meta-Analysis"],
  },
  {
    chunk_tag: "S20", source_id: "PMID:24518841", source_type: "pubmed", section: null,
    title: "Metformin and prostate cancer risk: a systematic review and meta-analysis",
    url: "https://pubmed.ncbi.nlm.nih.gov/24518841/", license: null,
    published_date: "2014-02-11", retrieved_at: "2026-07-04",
    authors: ["Kasznicki J", "Sliwinska A", "Drzewoski J"],
    journal: "Ann Transl Med", year: "2014", volume: "2", issue: "6", pages: "57",
    publication_types: ["Systematic Review"],
  },
  {
    chunk_tag: "S21", source_id: "PMID:30291106", source_type: "pubmed_oa", section: null,
    title: "Metformin exposure and survival in diabetic patients with colorectal cancer",
    url: "https://pubmed.ncbi.nlm.nih.gov/30291106/", license: "cc-by-nc",
    published_date: "2018-10-05", retrieved_at: "2026-07-04",
    authors: ["Meng F", "Song L", "Wang W"],
    journal: "Medicine (Baltimore)", year: "2018", volume: "97", issue: "40", pages: "e12628",
    publication_types: ["Observational Study"], doaj_vetted: true,
  },
  {
    chunk_tag: "S22", source_id: "PMID:22824948", source_type: "pubmed", section: null,
    title: "Metformin and reduced risk of hepatocellular carcinoma in diabetic patients",
    url: "https://pubmed.ncbi.nlm.nih.gov/22824948/", license: null,
    published_date: "2012-07-24", retrieved_at: "2026-07-04",
    authors: ["Chen HP", "Shieh JJ", "Chang CC", "Chen TT", "Lin JT", "Wu MS", "Lin JH", "Wu CY"],
    journal: "Gut", year: "2013", volume: "62", issue: "4", pages: "606-615",
    publication_types: ["Observational Study"],
  },
  {
    chunk_tag: "S23", source_id: "PMID:34019750", source_type: "pubmed", section: null,
    title: "Target-trial emulation of metformin initiation and cancer incidence in type 2 diabetes",
    url: "https://pubmed.ncbi.nlm.nih.gov/34019750/", license: null,
    published_date: "2021-05-21", retrieved_at: "2026-07-04",
    authors: ["Dickerman BA", "García-Albéniz X", "Logan RW", "Denaxas S", "Hernán MA"],
    journal: "Am J Epidemiol", year: "2021", volume: "190", issue: "8", pages: "1595-1604",
    publication_types: ["Observational Study"], doaj_vetted: true,
  },
  {
    chunk_tag: "S24", source_id: "PMID:29246585", source_type: "europepmc", section: null,
    title: "Metformin and endometrial cancer risk: a population-based case-control analysis",
    url: "https://europepmc.org/article/MED/29246585", license: null,
    published_date: "2017-12-15", retrieved_at: "2026-07-04",
    authors: ["Tseng CH", "Chong K", "Tai H"],
    journal: "Gynecol Oncol", year: "2018", volume: "148", issue: "3", pages: "550-556",
    publication_types: ["Observational Study"],
  },
  {
    chunk_tag: "S25", source_id: "PMID:23864498", source_type: "pubmed", section: null,
    title: "Confounding by disease severity in observational studies of metformin and cancer",
    url: "https://pubmed.ncbi.nlm.nih.gov/23864498/", license: null,
    published_date: "2013-07-18", retrieved_at: "2026-07-04",
    authors: ["Badrick E", "Renehan AG"],
    journal: "Eur J Cancer", year: "2014", volume: "50", issue: "12", pages: "2213-2220",
    publication_types: ["Review"],
  },
  {
    chunk_tag: "S26", source_id: "PMID:36109120", source_type: "pubmed", section: null,
    title: "Metformin and cancer incidence in non-diabetic populations: a scoping review",
    url: "https://pubmed.ncbi.nlm.nih.gov/36109120/", license: null,
    published_date: "2022-09-15", retrieved_at: "2026-07-04",
    authors: ["Ahmad E", "Sargeant JA", "Zaccardi F", "Khunti K", "Webb DR", "Davies MJ"],
    journal: "Diabetes Obes Metab", year: "2022", volume: "24", issue: "12", pages: "2299-2312",
    publication_types: ["Review"], doaj_vetted: true,
  },
  {
    chunk_tag: "S27", source_id: "NCT02948569", source_type: "clinicaltrials", section: null,
    title: "Metformin for Prevention of Colorectal Adenomas (Phase II Chemoprevention Trial)",
    url: "https://clinicaltrials.gov/study/NCT02948569", license: null,
    published_date: "2016-10-28", retrieved_at: "2026-07-04",
    year: "2016", study_type: "INTERVENTIONAL", trial_phase: "PHASE2",
  },
  {
    chunk_tag: "S28", source_id: "PMID:27013409", source_type: "pubmed", section: null,
    title: "Low-dose metformin for prevention of metachronous colorectal adenoma: a randomized trial",
    url: "https://pubmed.ncbi.nlm.nih.gov/27013409/", license: null,
    published_date: "2016-03-24", retrieved_at: "2026-07-04",
    authors: ["Higurashi T", "Hosono K", "Takahashi H", "Komiya Y", "Umezawa S", "Sakai E", "Uchiyama T", "Taniguchi L", "Hata Y", "Uchiyama S"],
    journal: "Lancet Oncol", year: "2016", volume: "17", issue: "4", pages: "475-483",
    publication_types: ["Randomized Controlled Trial"], doaj_vetted: true,
  },
  {
    chunk_tag: "S29", source_id: "PMID:32540528", source_type: "pubmed_oa", section: null,
    title: "Metformin and gastric cancer risk in type 2 diabetes: a nationwide propensity-matched cohort",
    url: "https://pubmed.ncbi.nlm.nih.gov/32540528/", license: "cc-by",
    published_date: "2020-06-15", retrieved_at: "2026-07-04",
    authors: ["Cheung KS", "Chan EW", "Wong AYS", "Chen L", "Seto WK", "Wong ICK", "Leung WK"],
    journal: "Gut", year: "2020", volume: "69", issue: "11", pages: "1988-1997",
    publication_types: ["Observational Study"], doaj_vetted: true, oa_url: "https://gut.bmj.com/content/69/11/1988",
  },
  {
    chunk_tag: "S30", source_id: "PMID:31677374", source_type: "pubmed", section: null,
    title: "Bias analysis and the metformin–cancer literature: a methodological synthesis",
    url: "https://pubmed.ncbi.nlm.nih.gov/31677374/", license: null,
    published_date: "2019-11-01", retrieved_at: "2026-07-04",
    authors: ["Renehan AG", "Yeh HC", "Johnson JA", "Wild SH", "Gale EAM", "Møller H"],
    journal: "Diabetologia", year: "2020", volume: "63", issue: "1", pages: "56-67",
    publication_types: ["Review"],
  },
];

const FIXTURE: ResearchReport = {
  question: "Does metformin reduce cancer incidence in adults with type 2 diabetes?",
  summary:
    "Early observational studies suggested people with type 2 diabetes taking metformin had lower cancer rates, but this signal shrinks sharply once time-related biases are corrected, and randomized-trial evidence does not confirm a protective effect. The honest bottom line: metformin is not established as a cancer-preventing drug, and the apparent benefit in older cohort studies is largely explained by how those studies were designed.",
  sub_questions: [
    "Do observational cohort studies show lower cancer incidence with metformin?",
    "Does the association survive correction for immortal time and confounding by indication?",
    "What do randomized controlled trials and meta-analyses of RCTs show?",
    "Does the effect differ by cancer site (colorectal, pancreatic, breast, others)?",
    "Do methodological bias-correction and target-trial approaches change the estimate?",
  ],
  sections: [
    {
      heading: "Observational studies show an association",
      points: [
        { text: "Early cohort studies reported that diabetic patients on metformin had a lower overall cancer incidence than those on other glucose-lowering therapies.", citation_ids: ["S1", "S2", "S13"] },
        { text: "A widely cited meta-analysis of observational data estimated roughly a 30% lower cancer risk associated with metformin use.", citation_ids: ["S3", "S14"] },
        { text: "Site-specific analyses suggested reduced colorectal, pancreatic, and hepatocellular cancer incidence, though effect sizes varied widely between studies.", citation_ids: ["S8", "S10", "S22"] },
        { text: "Smaller signals were reported for breast, lung, prostate, endometrial, and gastric cancers, but these were inconsistent across cohorts.", citation_ids: ["S16", "S19", "S20", "S24", "S29"] },
      ],
    },
    {
      heading: "The association weakens after correcting for bias",
      points: [
        { text: "Much of the apparent benefit reflects immortal time bias and other time-related biases in how metformin exposure was counted.", citation_ids: ["S4", "S5", "S15"] },
        { text: "When new-user designs and time-varying exposure are applied, the protective association attenuates substantially or disappears.", citation_ids: ["S9", "S30"] },
        { text: "A target-trial emulation designed to remove these biases found no clear reduction in cancer incidence after metformin initiation.", citation_ids: ["S23"] },
        { text: "Confounding by diabetes severity and by indication further inflates the apparent effect in prevalent-user comparisons.", citation_ids: ["S25"] },
      ],
    },
    {
      heading: "Randomized evidence does not confirm a protective effect",
      points: [
        { text: "A meta-analysis restricted to randomized controlled trials found no statistically significant reduction in cancer incidence with metformin.", citation_ids: ["S6"] },
        { text: "In early breast cancer, a large adjuvant randomized trial found no improvement in invasive disease-free survival with metformin versus placebo.", citation_ids: ["S17", "S18"] },
        { text: "A randomized chemoprevention trial reduced metachronous colorectal adenomas, but adenoma recurrence is a surrogate, not a cancer-incidence endpoint.", citation_ids: ["S27", "S28"] },
        { text: "An umbrella review of meta-analyses concluded the overall evidence for a cancer-preventive effect is low-certainty and inconsistent.", citation_ids: ["S12", "S26"] },
        { text: "Dedicated prevention trials are testing the question prospectively but have not yet delivered definitive incidence results.", citation_ids: ["S7", "S11"] },
      ],
    },
  ],
  uncertainties: [
    { text: "Whether any real anticancer effect exists at a specific site (e.g. colorectal) once high-quality prospective data mature.", citation_ids: ["S8", "S21"] },
  ],
  safety_notes: [
    { text: "Metformin should not be started or stopped for cancer prevention outside a clinical trial; its established use is glycemic control in type 2 diabetes.", citation_ids: ["S4"] },
  ],
  citations: CITATIONS,
  evidence_grade: "moderate",
  safety_flags: [],
  claims_verified: true,
  mode: "structured_review",
  gaps: [
    {
      dimension: "study_design", type: "no_rct", scope: "this_run",
      text: "No completed randomized trial in this run reports cancer incidence as a primary endpoint in an unselected type 2 diabetes population; the RCT evidence is secondary-outcome, surrogate-endpoint, or pooled.",
      denominator: { providers_searched: ["pubmed", "clinicaltrials", "europepmc"], n_sources: 30, retrieved_at: "2026-07-04" },
      corroborating_trials: ["NCT01101438", "NCT02614339", "NCT02948569"],
    },
    {
      dimension: "long_term", type: "sparse", scope: "this_run",
      text: "Long-term (>10 year) incidence data are sparse; most cohorts followed patients for a median under 6 years.",
      denominator: { providers_searched: ["pubmed", "europepmc"], n_sources: 30, retrieved_at: "2026-07-04" },
      corroborating_trials: [],
    },
  ],
  search_method: {
    databases: ["PubMed", "ClinicalTrials.gov", "Europe PMC"],
    queries: [
      "metformin cancer incidence type 2 diabetes",
      "metformin cancer risk immortal time bias",
      "metformin cancer randomized controlled trial meta-analysis",
      "metformin site-specific cancer breast colorectal pancreatic",
      "metformin cancer target trial emulation confounding",
    ],
    search_date: "2026-07-04",
    inclusion_notes: "Human studies in type 2 diabetes reporting cancer incidence; observational cohorts, RCTs, and syntheses.",
    exclusion_notes: "Excluded in-vitro/animal work, case reports, and studies without a diabetes-population denominator.",
  },
  counts: {
    per_provider: { pubmed: 61, clinicaltrials: 9, europepmc: 14, pubmed_oa: 12 },
    total_retrieved: 96,
    n_searches: 5,
    per_search_cap: 12,
    retrieved_at: "2026-07-04",
  },
  citation_style: "vancouver",
  // Poolable meta-analysis so the preview exercises the forest-plot band. Realistic 2x2 counts →
  // the real poolRiskRatio math would produce these figures; hand-set here for a static fixture.
  meta_analysis: {
    poolable: true,
    measure: "risk_ratio",
    k: 5,
    studies: [
      { label: "Evans 2005 (ZODIAC)", citation_tag: "3", outcome_label: "cancer incidence", events_treatment: 45, total_treatment: 1200, events_control: 78, total_control: 1100, effect_log: Math.log(0.53), effect: 0.53, variance: 0.04, ci_low: 0.37, ci_high: 0.76, weight_percent: 22, continuity_corrected: false, source_quote: "" },
      { label: "Libby 2009", citation_tag: "7", outcome_label: "cancer incidence", events_treatment: 120, total_treatment: 4085, events_control: 100, total_control: 1465, effect_log: Math.log(0.63), effect: 0.63, variance: 0.02, ci_low: 0.49, ci_high: 0.81, weight_percent: 28, continuity_corrected: false, source_quote: "" },
      { label: "Currie 2009", citation_tag: "11", outcome_label: "cancer incidence", events_treatment: 210, total_treatment: 6200, events_control: 190, total_control: 3100, effect_log: Math.log(0.79), effect: 0.79, variance: 0.015, ci_low: 0.63, ci_high: 0.99, weight_percent: 26, continuity_corrected: false, source_quote: "" },
      { label: "Bodmer 2010", citation_tag: "16", outcome_label: "cancer incidence", events_treatment: 30, total_treatment: 900, events_control: 40, total_control: 850, effect_log: Math.log(0.70), effect: 0.70, variance: 0.06, ci_low: 0.44, ci_high: 1.12, weight_percent: 14, continuity_corrected: false, source_quote: "" },
      { label: "Ruiter 2012", citation_tag: "21", outcome_label: "cancer incidence", events_treatment: 18, total_treatment: 620, events_control: 22, total_control: 580, effect_log: Math.log(0.76), effect: 0.76, variance: 0.10, ci_low: 0.41, ci_high: 1.41, weight_percent: 10, continuity_corrected: false, source_quote: "" },
    ],
    fixed: { estimate: 0.67, estimate_log: Math.log(0.67), variance: 0.0075, ci_low: 0.58, ci_high: 0.78 },
    random: { estimate: 0.68, estimate_log: Math.log(0.68), variance: 0.0095, ci_low: 0.57, ci_high: 0.81 },
    heterogeneity: { q: 5.1, df: 4, i2: 22, tau2: 0.01 },
  },
};

export default function PosterPreviewPage() {
  return (
    <div className="poster-preview-stage">
      <ResearchPoster report={FIXTURE} style="vancouver" />
    </div>
  );
}
