// Turning a formula into points, so the plot renderer draws it and nothing new has to (§45).
//
// 🔴 THIS IS THE SAFE HALF OF "LET THE MODEL CODE IT". The model writes a CALCULATION; this module
// runs it under `expression.ts`'s allow list and hands back numbers; the plot renderer that already
// existed draws them. Nothing model-written reaches the DOM, the picture stays deterministic, the
// points can be checked, and a curve can be occluded and marked against exactly like any other plot.
// The alternative — the model emitting SVG or chart configuration — gives pixels nobody can check.
//
// 🔴 SO THERE IS NO NEW VISUAL KIND HERE, AND THAT IS THE DESIGN. A function plot IS a quantitative
// plot whose points were computed rather than listed. Adding a `function` representation would have
// meant a second plot renderer, a second set of axis rules, and two places for a chart to look
// different from itself.
//
// 🔴 RUNS WHERE A LESSON IS BUILT, NEVER IN THE LEARNER'S BROWSER. It pulls in a maths parser, which
// has no business in a page that only has to draw a polyline.

import { checkExpression, type ExpressionRefusal } from "./expression";
import { densityAt, histogram, sample, type DistributionRefusal, type DistributionSpec } from "./statistics";

/** One run of points with no gap in it. */
export interface Segment {
  readonly points: readonly { x: number; y: number }[];
}

export type ComputedRefusal =
  | ExpressionRefusal
  | DistributionRefusal
  /** The domain is empty, backwards, or not numbers. */
  | "domain-unusable"
  /** Asked for more or fewer sample points than a curve is drawn from. */
  | "sample-count-unusable"
  /**
   * The expression has no value anywhere in the domain.
   *
   * 🔴 ITS OWN REASON RATHER THAN AN EMPTY PLOT. `sqrt(x)` from −10 to −1 is a legitimate formula
   * asked over the wrong range, and an empty chart would look like a rendering failure instead of
   * saying that the question was about a region where the function does not exist.
   */
  | "nothing-to-plot";

export type Computed<T> = { ok: true; value: T } | { detail: string; ok: false; reason: ComputedRefusal };

/**
 * How many points a curve is drawn from.
 *
 * 🔴 THE OLD PLOT BOUND WAS 40 POINTS PER SERIES AND THAT WAS RIGHT FOR HAND-WRITTEN DATA. A model
 * listing forty points is a table; a model listing four hundred is a runaway. But a COMPUTED curve
 * is generated by trusted code, and forty points across a sine wave is a visible polygon. The bound
 * moved up for everyone rather than being made conditional, because a validator cannot tell a
 * computed series from a claimed one — and the risk of a large point count is payload size, which
 * bounding at 400 handles, not correctness.
 */
export const DEFAULT_SAMPLES = 160;
const MIN_SAMPLES = 8;
const MAX_SAMPLES_PER_CURVE = 400;

export interface CurveRequest {
  readonly expression: string;
  readonly from: number;
  readonly to: number;
  /** Defaults to `x`. */
  readonly variable?: string;
  readonly samples?: number;
}

/**
 * Evaluate an expression across a range.
 *
 * 🔴 GAPS SPLIT THE CURVE INSTEAD OF BEING SKIPPED, AND THIS IS NOT COSMETIC. The plot renderer
 * draws a polyline through consecutive points, so dropping the undefined point in `1/x` at zero
 * joins −0.01 to +0.01 with a line straight across the asymptote — a picture of a function that
 * passes through the origin, which is the opposite of what is being taught. Each continuous run
 * comes back as its own segment.
 */
export function curve(request: CurveRequest): Computed<Segment[]> {
  const variable = request.variable ?? "x";
  const checked = checkExpression(request.expression, [variable]);
  if (!checked.ok) return { detail: checked.detail, ok: false, reason: checked.reason };

  const { from, to } = request;
  if (!Number.isFinite(from) || !Number.isFinite(to) || from === to) {
    return { detail: `the domain ${from} to ${to} has no width`, ok: false, reason: "domain-unusable" };
  }
  const low = Math.min(from, to);
  const high = Math.max(from, to);

  const samples = request.samples ?? DEFAULT_SAMPLES;
  if (!Number.isInteger(samples) || samples < MIN_SAMPLES || samples > MAX_SAMPLES_PER_CURVE) {
    return {
      detail: `${samples} sample points, and a curve is drawn from ${MIN_SAMPLES}–${MAX_SAMPLES_PER_CURVE}`,
      ok: false,
      reason: "sample-count-unusable",
    };
  }

  const step = (high - low) / (samples - 1);
  const raw: Array<{ x: number; y: number } | null> = [];
  for (let index = 0; index < samples; index += 1) {
    const x = low + index * step;
    raw.push(((value) => (value === null ? null : { x, y: value }))(checked.evaluate({ [variable]: x })));
  }

  // 🔴 A POLE IS NOT A HOLE, AND MISSING THAT WAS A REAL DEFECT. `1/x` sampled across zero never
  // lands exactly ON zero — with 160 points from −5 to 5 the nearest sample sits at ±0.03 — so the
  // function is finite at every point and nothing was undefined. The curve came back as ONE run and
  // the renderer drew a line from −31.8 straight up to +31.8 through the origin: a picture of a
  // function that is continuous at exactly the place the lesson is about.
  //
  // 🔴 SO THE SPLIT IS A HEURISTIC, AND IT IS NARROW ON PURPOSE. Adjacent points are treated as
  // spanning a pole only when they have OPPOSITE SIGNS and both are large compared with the typical
  // magnitude of the curve. An ordinary zero crossing fails the second half (the values are small
  // there), and a steep-but-continuous curve like `e^x` fails the first (no sign change). What this
  // cannot detect is a pole that does not flip sign, such as `1/x^2` — that draws a spike up and
  // back down, which is at least the right shape.
  const magnitudes = raw.filter((point): point is { x: number; y: number } => point !== null).map((point) => Math.abs(point.y));
  const typical = magnitudes.length > 0 ? median(magnitudes) : 0;
  const poleThreshold = Math.max(typical * 10, 1e-9);

  const segments: Array<{ points: Array<{ x: number; y: number }> }> = [];
  let current: Array<{ x: number; y: number }> = [];
  let previous: { x: number; y: number } | null = null;

  for (const point of raw) {
    if (point === null) {
      if (current.length > 1) segments.push({ points: current });
      current = [];
      previous = null;
      continue;
    }
    const crossesPole =
      previous !== null &&
      Math.sign(point.y) !== Math.sign(previous.y) &&
      Math.abs(point.y) > poleThreshold &&
      Math.abs(previous.y) > poleThreshold;
    if (crossesPole) {
      if (current.length > 1) segments.push({ points: current });
      current = [];
    }
    current.push(point);
    previous = point;
  }
  if (current.length > 1) segments.push({ points: current });

  if (segments.length === 0) {
    return {
      detail: `"${request.expression}" has no value anywhere between ${low} and ${high}`,
      ok: false,
      reason: "nothing-to-plot",
    };
  }
  return { ok: true, value: segments };
}

/** The middle value of a list, used to judge what "large" means for one particular curve. */
function median(values: readonly number[]): number {
  const sorted = [...values].sort((a, b) => a - b);
  if (sorted.length === 0) return 0;
  const middle = Math.floor(sorted.length / 2);
  const high = sorted[middle] ?? 0;
  return sorted.length % 2 === 0 ? ((sorted[middle - 1] ?? high) + high) / 2 : high;
}

/**
 * The curve of a distribution's density across a range.
 *
 * Discrete distributions are sampled at whole numbers only, because a binomial has no value at 3.5
 * and drawing one would invent a shape the mathematics does not have.
 */
export function distributionCurve(spec: DistributionSpec, from: number, to: number, samples = DEFAULT_SAMPLES): Computed<Segment[]> {
  if (!Number.isFinite(from) || !Number.isFinite(to) || from === to) {
    return { detail: `the range ${from} to ${to} has no width`, ok: false, reason: "domain-unusable" };
  }
  const low = Math.min(from, to);
  const high = Math.max(from, to);
  const discrete = spec.kind === "binomial" || spec.kind === "poisson";
  const points: Array<{ x: number; y: number }> = [];

  if (discrete) {
    for (let k = Math.ceil(low); k <= Math.floor(high); k += 1) {
      const density = densityAt(spec, k);
      if (!density.ok) return { detail: density.detail, ok: false, reason: density.reason };
      points.push({ x: k, y: density.value });
    }
  } else {
    const count = Math.min(Math.max(samples, MIN_SAMPLES), MAX_SAMPLES_PER_CURVE);
    const step = (high - low) / (count - 1);
    for (let index = 0; index < count; index += 1) {
      const x = low + index * step;
      const density = densityAt(spec, x);
      if (!density.ok) return { detail: density.detail, ok: false, reason: density.reason };
      points.push({ x, y: density.value });
    }
  }

  if (points.length < 2) {
    return { detail: "this range contains fewer than two points of the distribution", ok: false, reason: "nothing-to-plot" };
  }
  return { ok: true, value: [{ points }] };
}

/**
 * Draw a sample, and return the shape it made.
 *
 * 🔴 THE SEED TRAVELS BACK OUT WITH THE POINTS. A histogram is only a teaching object if the same
 * question produces the same bars, and the only way a caller can store "this is the simulation the
 * learner saw" is to store what produced it.
 */
export function sampledHistogram(
  spec: DistributionSpec,
  count: number,
  seed: number,
  bins = 12,
): Computed<{ points: Array<{ x: number; y: number }>; seed: number; summarySource: number[] }> {
  const drawn = sample(spec, count, seed);
  if (!drawn.ok) return { detail: drawn.detail, ok: false, reason: drawn.reason };
  const boundedBins = Math.min(Math.max(Math.round(bins), 3), 40);
  const counted = histogram(drawn.value, boundedBins);
  if (counted.length === 0) {
    return { detail: "the sample produced no bins", ok: false, reason: "nothing-to-plot" };
  }
  return {
    ok: true,
    value: {
      // The bin's midpoint, so a bar chart drawn as a line lands over the interval it counts rather
      // than at its left edge.
      points: counted.map((bin) => ({ x: (bin.from + bin.to) / 2, y: bin.count })),
      seed,
      summarySource: drawn.value,
    },
  };
}
