// Builds apps/web/space/app/emoji.js (the emoji picker's sections and search words) from emojibase-data (MIT),
// whose names and keywords come from Unicode CLDR. Run: node apps/web/scripts/space-emoji.mjs
import { writeFileSync, readFileSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const web = path.resolve(here, "..");
const require = createRequire(import.meta.url);
const root = path.dirname(require.resolve("emojibase-data/package.json"));
const data = JSON.parse(readFileSync(path.join(root, "en/data.json"), "utf8"));
const shortcodes = JSON.parse(readFileSync(path.join(root, "en/shortcodes/emojibase.json"), "utf8"));
const version = JSON.parse(readFileSync(path.join(root, "package.json"), "utf8")).version;

// Emoji newer than 15.0 draw as empty boxes on phones and laptops a year or two old, so the picker leaves them out.
const MAX_VERSION = 15;
// Unicode's groups, in picker order. Smileys and people read as one section; skin-tone components are not emoji to pick.
const SECTIONS = [
  ["People", [0, 1]],
  ["Animals and nature", [3]],
  ["Food and drink", [4]],
  ["Activities", [6]],
  ["Travel and places", [5]],
  ["Objects", [7]],
  ["Symbols", [8]],
  ["Flags", [9]],
];

const usable = data
  .filter((e) => typeof e.group === "number" && e.group !== 2 && (e.version ?? 0) <= MAX_VERSION)
  .sort((a, b) => (a.order ?? 0) - (b.order ?? 0));

const sections = SECTIONS.map(([name, groups]) => [
  name,
  usable.filter((e) => groups.includes(e.group)).map((e) => [e.emoji, e.label]),
]);

const keywords = {};
for (const e of usable) {
  const words = [e.label, ...(e.tags ?? []), ...[].concat(shortcodes[e.hexcode] ?? []).map((s) => s.replace(/_/g, " "))];
  keywords[e.emoji] = [...new Set(words.map((w) => String(w).toLowerCase()))].join("|");
}

writeFileSync(
  path.join(web, "space/app/emoji.js"),
  `// GENERATED by apps/web/scripts/space-emoji.mjs from emojibase-data ${version} (MIT; names and keywords from Unicode CLDR).\n` +
    `// [section, [[emoji, name], ...]] in Unicode order, emoji ${MAX_VERSION}.0 and older.\n` +
    `export const EMOJI_SECTIONS = ${JSON.stringify(sections)};\n` +
    `// Search words per emoji: its name first, then CLDR keywords and shortcodes.\n` +
    `export const EMOJI_KW = ${JSON.stringify(keywords)};\n`,
);
console.log(`emoji.js: ${usable.length} emoji in ${sections.length} sections`);
