// Builds apps/web/space/app/icons.js and page-icons.js from Lucide, the one icon library /design/ICONS.md allows.
//
// The Space frontend asks for icons by name (`<Icon n="viewTable"/>`); space/icons/map.json says which Lucide glyph
// each name draws. Nothing here is drawn by hand, and nothing is copied from another product's icon set.
//
// 🔴 COLOUR TRAVELS AS --nsp-fill, NOT currentColor. The Space stylesheet colours icons the way its layout was
// measured: by setting `fill` on a container (a sidebar row, a menu item) while `color` carries the text, often in a
// different shade. Lucide draws with strokes, so every `fill:` in space.css also publishes `--nsp-fill`
// (scripts/space-scope-css.mjs) and every glyph strokes with it.
//
// Run: node apps/web/scripts/space-icons.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const web = path.resolve(here, "..");
const require = createRequire(import.meta.url);
const lucideRoot = path.dirname(require.resolve("lucide-react/package.json"));
const iconsDir = path.join(lucideRoot, "dist/esm/icons");
const license = readFileSync(path.join(lucideRoot, "LICENSE"), "utf8").trim();
const version = JSON.parse(readFileSync(path.join(lucideRoot, "package.json"), "utf8")).version;

// The Nemesis mark (design/BRAND.md): three dots, two up and one down, drawn from the brand geometry.
const MARK = '<svg viewBox="0 0 24 24" aria-hidden="true" style="fill:var(--nsp-fill,currentColor)"><circle cx="7.4" cy="8.6" r="3.6"></circle><circle cx="16.6" cy="8.6" r="3.6"></circle><circle cx="12" cy="16.4" r="3.6"></circle></svg>';

const esc = (v) => String(v).replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;");

async function nodeOf(name, seen = new Set()) {
  if (seen.has(name)) throw new Error(`alias loop at ${name}`);
  seen.add(name);
  const file = path.join(iconsDir, `${name}.mjs`);
  let text;
  try {
    text = readFileSync(file, "utf8");
  } catch {
    return null;
  }
  const alias = text.match(/export \{ default \} from '\.\/([a-z0-9-]+)\.mjs'/);
  if (alias && !text.includes("__iconNode")) return nodeOf(alias[1], seen);
  const mod = await import(pathToFileURL(file).href);
  return { node: mod.__iconNode, canonical: name };
}

function inner(node) {
  return node
    .map(([tag, attrs]) => `<${tag} ${Object.entries(attrs).filter(([k]) => k !== "key").map(([k, v]) => `${k}="${esc(v)}"`).join(" ")}></${tag}>`)
    .join("");
}

function svg(node, fill) {
  // 🔴 `fill:none` INLINE, NOT AS AN ATTRIBUTE. The measured stylesheet sets `.nicon svg { fill: inherit }`, and a CSS
  // rule beats a presentation attribute, so every closed shape (a rectangle, a circle, a star) came out solid.
  const style = fill ? "fill:var(--nsp-fill,currentColor);stroke:var(--nsp-fill,currentColor)" : "fill:none;stroke:var(--nsp-fill,currentColor)";
  return `<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" style="${style}">${inner(node)}</svg>`;
}

const header = (what) => `// GENERATED by apps/web/scripts/space-icons.mjs from lucide-react ${version}. Do not edit; edit space/icons/map.json.
// ${what}
/*
${license}
*/
`;

const map = JSON.parse(readFileSync(path.join(web, "space/icons/map.json"), "utf8"));
const out = {};
const missing = [];
for (const [key, spec] of Object.entries(map)) {
  const name = typeof spec === "string" ? spec : spec.lucide;
  const fill = typeof spec === "object" && spec.fill === true;
  if (name === "@mark") {
    out[key] = MARK;
    continue;
  }
  const found = await nodeOf(name);
  if (!found) {
    missing.push(`${key} -> ${name}`);
    continue;
  }
  out[key] = svg(found.node, fill);
}
if (missing.length) {
  console.error("Lucide has no icon named:\n  " + missing.join("\n  "));
  process.exit(1);
}

// Property-type glyphs drawn through CSS masks (a table header's icon is a mask over its text colour).
const MASK_ICONS = { font: "type", burst: "loader", arrowCircleDown: "circle-chevron-down", list: "list", calendar: "calendar" };
const masks = {};
for (const [key, name] of Object.entries(MASK_ICONS)) {
  const found = await nodeOf(name);
  if (!found) throw new Error(`mask ${key}: Lucide has no ${name}`);
  const raw = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="black" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">${inner(found.node)}</svg>`;
  masks[key] = "data:image/svg+xml," + encodeURIComponent(raw);
}
writeFileSync(
  path.join(web, "space/app/icons.js"),
  header("Interface icons, by the name the Space frontend asks for.") +
    `export const ICONS = ${JSON.stringify(out, null, 0).replace(/","/g, '",\n"')};\n` +
    `export const MASKS = ${JSON.stringify(masks)};\n`,
);

// Page icons: every Lucide glyph once (aliases skipped), for the icon picker. Loaded only when the picker opens.
const files = (await import("node:fs")).readdirSync(iconsDir).filter((f) => f.endsWith(".mjs"));
const pageIcons = [];
for (const f of files.sort()) {
  const text = readFileSync(path.join(iconsDir, f), "utf8");
  if (!text.includes("__iconNode")) continue;
  const mod = await import(pathToFileURL(path.join(iconsDir, f)).href);
  pageIcons.push([f.replace(/\.mjs$/, ""), inner(mod.__iconNode)]);
}
writeFileSync(
  path.join(web, "space/app/page-icons.js"),
  header("Page icons for the picker: [name, svg children], drawn at 24 by 24 with a 1.5 stroke.") +
    `export const PAGE_ICONS = [\n${pageIcons.map((p) => JSON.stringify(p)).join(",\n")}\n];\n`,
);
console.log(`icons.js: ${Object.keys(out).length} names; page-icons.js: ${pageIcons.length} glyphs`);
