// Getting work out of the studio.
//
// Four ways out, and they are for different people:
//
//  · JSON — the whole document, to back up or hand to someone else. Round-trips.
//  · TypeScript — the faces as a paste-ready block for `lib/mascot/expressions.ts`.
//    This is the one that makes the studio load-bearing rather than a toy: a face
//    authored here becomes a face the product ships, without anyone retyping six
//    numbers and getting one of them wrong.
//  · SVG — the frame on screen, as a file.
//  · PNG — the same frame, rasterised.
//
// 🔴 THE PICTURE IS SERIALISED FROM THE LIVE NODE, NOT RE-RENDERED. Re-rendering to a
// string would mean a second implementation of the renderer, which is the same trap as
// a second renderer of the engine: it agrees with the first one until it quietly does
// not, and the disagreement shows up as "the export does not look like the studio". The
// element on screen is already the artefact; this just copies it.

import type { StudioCharacter, StudioDoc, StudioExpression } from "./document";

// ── JSON ────────────────────────────────────────────────────────────────────────

export function docToJson(doc: StudioDoc): string {
  return JSON.stringify(doc, null, 2);
}

export function characterToJson(character: StudioCharacter): string {
  return JSON.stringify(character, null, 2);
}

// ── TypeScript ──────────────────────────────────────────────────────────────────

/** Trims a float to the shortest form that still reads back identically. */
function short(n: number): string {
  for (let places = 0; places <= 4; places++) {
    const s = n.toFixed(places);
    if (Number(s) === Number(n.toFixed(4))) return String(Number(s));
  }
  return String(Number(n.toFixed(4)));
}

/**
 * A TypeScript identifier for a face, from whatever the author typed as its name.
 *
 * 🔴 THE RESULT HAS TO BE A LEGAL IDENTIFIER, not merely a tidy string. This block is
 * pasted straight into `expressions.ts`, so a key that needs quoting turns every call
 * site from `EXPRESSIONS.deepThought` into `EXPRESSIONS["deep thought"]` — and a key
 * beginning with a digit does not compile at all. A face called "123 go" is not a silly
 * input; it is what you get when someone names faces by number.
 */
export function keyFor(e: StudioExpression): string {
  const slug = e.name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  const base =
    slug.length > 0
      ? // A hyphenated key is legal in an object literal but only as a quoted string, and
        // `EXPRESSIONS["deep-thought"]` is worse to use than `EXPRESSIONS.deepThought`.
        slug.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase())
      : e.id.replace(/[^a-z0-9]+/gi, "");
  // Underscore rather than a dropped digit: "123 go" and "23 go" must not collide.
  return /^[0-9]/.test(base) || base.length === 0 ? `_${base}` : base;
}

const escape = (s: string): string => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');

/**
 * The faces as entries for `EXPRESSIONS` in `lib/mascot/expressions.ts`.
 *
 * Emitted as the whole object body rather than as a diff, because a paste that replaces
 * a known block is reviewable and a paste that has to be merged by hand is not.
 */
export function expressionsToTypeScript(character: StudioCharacter): string {
  const lines: string[] = [
    "// Generated by the character studio (/character-studio).",
    `// Character: ${character.name}. Paste over the EXPRESSIONS body in lib/mascot/expressions.ts.`,
    "//",
    "// Every value is a MULTIPLIER or an OFFSET on what the state already decided — see the",
    "// note at the top of that file. Nothing here is an absolute.",
    "",
    "export const EXPRESSIONS = {",
  ];
  for (const e of character.expressions) {
    const note = e.note.trim().length > 0 ? e.note.trim() : `${e.name}.`;
    lines.push(`  /** ${note.replace(/\*\//g, "*​/")} */`);
    lines.push(
      `  ${keyFor(e)}: { label: "${escape(e.name)}", note: "${escape(note)}", ` +
        `h: ${short(e.h)}, w: ${short(e.w)}, rise: ${short(e.rise)}, ` +
        `tilt: ${short(e.tilt)}, asym: ${short(e.asym)}, curve: ${short(e.curve)} },`,
    );
  }
  lines.push("} as const satisfies Record<string, ExpressionDef>;");
  lines.push("");
  return lines.join("\n");
}

// ── Pictures ────────────────────────────────────────────────────────────────────

/**
 * The SVG on screen as standalone markup.
 *
 * 🔴 THE CSS VARIABLES ARE RESOLVED BEFORE SERIALISING. The renderer fills with
 * `var(--mascot-ink)`, which is defined on an ancestor stylesheet that a downloaded file
 * does not have — so the naive serialisation is a black-on-black square, and it fails
 * this way only OUTSIDE the browser, which is where nobody is looking. Every `fill` and
 * `stroke` referring to a variable is replaced with the computed colour on a clone.
 */
export function svgMarkup(node: SVGSVGElement): string {
  const clone = node.cloneNode(true) as SVGSVGElement;
  const source = node.querySelectorAll<SVGElement>("*");
  const copies = clone.querySelectorAll<SVGElement>("*");

  const resolve = (from: Element, to: SVGElement) => {
    const computed = window.getComputedStyle(from);
    for (const prop of ["fill", "stroke", "opacity", "stop-color"] as const) {
      const attr = to.getAttribute(prop);
      if (attr !== null && attr.includes("var(")) {
        const value = computed.getPropertyValue(prop);
        if (value.trim().length > 0) to.setAttribute(prop, value.trim());
      }
    }
  };
  resolve(node, clone);
  for (let i = 0; i < copies.length && i < source.length; i++) {
    resolve(source[i]!, copies[i]!);
  }

  clone.setAttribute("xmlns", "http://www.w3.org/2000/svg");
  clone.removeAttribute("style");
  return new XMLSerializer().serializeToString(clone);
}

export interface PictureOptions {
  /** Rasterised width in px. Height follows the viewBox ratio. */
  readonly width: number;
  /** `null` for transparent. */
  readonly background: string | null;
}

/**
 * The frame as a PNG blob.
 *
 * Goes through an `Image` and a canvas rather than any library. The one sharp edge is
 * that the SVG must be self-contained by the time it becomes a data URL — no external
 * fonts, no CSS variables — which `svgMarkup` has already handled.
 */
export async function svgToPng(markup: string, opts: PictureOptions): Promise<Blob> {
  const url = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(markup)}`;
  const img = new Image();
  img.decoding = "sync";
  await new Promise<void>((resolve, reject) => {
    img.onload = () => resolve();
    img.onerror = () => reject(new Error("The frame could not be rasterised."));
    img.src = url;
  });

  const ratio = img.naturalWidth > 0 ? img.naturalHeight / img.naturalWidth : 1;
  const w = Math.max(1, Math.round(opts.width));
  const h = Math.max(1, Math.round(w * ratio));

  const canvas = document.createElement("canvas");
  canvas.width = w;
  canvas.height = h;
  const ctx = canvas.getContext("2d");
  if (ctx === null) throw new Error("This browser would not give the studio a canvas.");
  if (opts.background !== null) {
    ctx.fillStyle = opts.background;
    ctx.fillRect(0, 0, w, h);
  }
  ctx.drawImage(img, 0, 0, w, h);

  return await new Promise<Blob>((resolve, reject) => {
    canvas.toBlob((blob) => {
      if (blob) resolve(blob);
      else reject(new Error("The frame could not be encoded as a PNG."));
    }, "image/png");
  });
}

// ── Handing a file to the browser ───────────────────────────────────────────────

export function download(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.append(a);
  a.click();
  a.remove();
  // Revoked on the next turn of the loop rather than immediately: revoking synchronously
  // after `click()` races the download in Safari and produces an empty file.
  window.setTimeout(() => URL.revokeObjectURL(url), 10_000);
}

export function downloadText(text: string, filename: string, type: string): void {
  download(new Blob([text], { type: `${type};charset=utf-8` }), filename);
}

/** A filename-safe version of a character or animation name. */
export function slug(name: string): string {
  const s = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return s.length > 0 ? s : "character";
}
