/**
 * The PDF routing decision, pinned from both sides.
 *
 * 🔴 EVERY THRESHOLD HERE IS PINNED TWICE — ONCE FROM BELOW AND ONCE FROM ABOVE. A test that only
 * proves "clean text routes native" would still pass if the constant were raised until nothing
 * ever escalated, which is the exact failure mode a cost-reduction change is most likely to have.
 * The calibration run (`scripts/preflight-calibrate.mts`, corpus generated by
 * `scripts/make-preflight-corpus.mjs`) measured a gap with clean documents at a corruption and
 * scar share of exactly 0.00000 and the broken-font class at 0.02535. Both constants sit inside
 * that gap, an order of magnitude clear of each edge, and these tests fail if either edge moves.
 */

import assert from "node:assert/strict";
import test from "node:test";

import {
  MAX_CORRUPT_CHAR_SHARE,
  MAX_LIGATURE_SCAR_SHARE,
  MIN_WORDS_FOR_RATE,
  pageEscalationSafe,
  preflightPdf,
  type NativePdfEvidence,
} from "./preflight";

/** A page of ordinary prose, long enough to clear both the thin-page floor and the rate floor. */
function cleanPage(seed: number): string {
  const sentence =
    "A document states what it contains before anything reads it and every locator must point at something real. ";
  return `Section ${seed}. ${sentence.repeat(6)}`;
}

function evidence(overrides: Partial<NativePdfEvidence> = {}): NativePdfEvidence {
  const pageTexts = overrides.pageTexts ?? [cleanPage(1), cleanPage(2), cleanPage(3)];
  return {
    declaredUnits: pageTexts.length,
    pageTexts,
    structureFailed: false,
    tableRegionsUnreadByUnit: [],
    tablesRejected: {},
    unitsWithContent: pageTexts.map((_, index) => index),
    visionAffordablePages: Number.MAX_SAFE_INTEGER,
    ...overrides,
  };
}

test("a clean digitally generated PDF never reaches a paid parser", () => {
  const verdict = preflightPdf(evidence());
  assert.equal(verdict.route, "native");
  assert.equal(verdict.reason, "native-read-sufficient");
  assert.equal(verdict.signals.corruptShare, 0);
  assert.equal(verdict.signals.scarShare, 0);
});

test("🔴 ordinary alphanumeric vocabulary is not a broken ligature", () => {
  // Every one of these is a real token from a real discipline, and not one of them is a scar:
  // the digit sits at an edge or has fewer than two letters on one side. If this ever fails, the
  // detector has started reading chemistry, virology, versioning and section numbers as damage.
  const page =
    "COVID19 H2O Fe2O3 3D p53 v2 Section4 Rule12 CD4 IPv6 mRNA B12 T4 ISO9001 alpha2 " +
    cleanPage(1);
  const verdict = preflightPdf(evidence({ pageTexts: [page, cleanPage(2)] }));
  assert.equal(verdict.route, "native");
  assert.equal(verdict.signals.scars, 0);
});

test("🔴 the broken-ligature signature escalates, and names itself", () => {
  // The measured shape: `action` -> `ac1on`, `contraindications` -> `contraindica1ons`.
  const damaged =
    "The ac1on of the agent is described in the sec1on above and the contraindica1ons are listed " +
    "with the indica1ons, the interac1ons and the precau1ons that apply to administra1on. " +
    cleanPage(1);
  const verdict = preflightPdf(evidence({ pageTexts: [damaged, damaged] }));
  assert.equal(verdict.route, "vendor");
  assert.equal(verdict.reason, "glyph-substitution");
  assert.ok(verdict.signals.scarShare > MAX_LIGATURE_SCAR_SHARE);
  assert.equal(verdict.pages, null, "a broken font is a document-wide cause and never page-wise");
});

test("🔴 a private-use alphabet escalates — the text layer that extracts as gibberish", () => {
  // A subsetted font with no ToUnicode CMap maps its glyphs into U+E000.., so the page "has text"
  // and none of it is readable. No fixture can produce this with a standard font, which is why it
  // is pinned here with the extracted text supplied directly.
  const pua = " ".repeat(30);
  const verdict = preflightPdf(evidence({ pageTexts: [`${cleanPage(1)} ${pua}`, cleanPage(2)] }));
  assert.equal(verdict.route, "vendor");
  assert.equal(verdict.reason, "corrupt-text-layer");
  assert.ok(verdict.signals.corruptShare > MAX_CORRUPT_CHAR_SHARE);
});

test("🔴 the replacement character counts as corruption, and one stray one does not", () => {
  const oneBadChar = `${cleanPage(1)}�`;
  assert.equal(preflightPdf(evidence({ pageTexts: [oneBadChar, cleanPage(2), cleanPage(3)] })).route, "native");

  const many = `${cleanPage(1)}${"�".repeat(40)}`;
  const verdict = preflightPdf(evidence({ pageTexts: [many] }));
  assert.equal(verdict.route, "vendor");
  assert.equal(verdict.reason, "corrupt-text-layer");
});

test("🔴 a lost grid escalates on the first one — there is no acceptable rate of losing a table", () => {
  const verdict = preflightPdf(evidence({ tableRegionsUnreadByUnit: [{ count: 1, unit: 1 }] }));
  assert.equal(verdict.route, "vendor");
  assert.equal(verdict.reason, "table-not-recovered");
  assert.equal(verdict.pages, null, "a table can span a page break, so half a grid is never enough");
});

test("a recovered grid is not a lost one", () => {
  // `tablesRejected` is carried for observability and must not, on its own, spend money: the page
  // kept its prose, and the deterministic lattice refusing an unruled candidate is the system
  // working. Escalating on it would pay a vendor every time the validator did its job.
  const verdict = preflightPdf(evidence({ tablesRejected: { "too-few-rows": 3 } }));
  assert.equal(verdict.route, "native");
  assert.equal(verdict.signals.tablesRejected, 3);
});

test("🔴 a structural read that threw escalates — we hold no structure to judge", () => {
  const verdict = preflightPdf(evidence({ declaredUnits: 0, pageTexts: [], structureFailed: true }));
  assert.equal(verdict.route, "vendor");
  assert.equal(verdict.reason, "structure-unavailable");
});

test("a document that is entirely pixels goes whole to the specialist", () => {
  const verdict = preflightPdf(
    evidence({ pageTexts: ["", "", ""], unitsWithContent: [0, 1, 2] }),
  );
  assert.equal(verdict.route, "vendor");
  assert.equal(verdict.reason, "no-text-layer");
  assert.equal(verdict.pages, null);
});

test("🔴 a blank file is never billed to be told it is blank", () => {
  // The defect the first calibration run caught: no text layer looks exactly like a scan until you
  // ask whether the reader located anything at all on the page.
  const verdict = preflightPdf(evidence({ pageTexts: ["", ""], unitsWithContent: [] }));
  assert.equal(verdict.route, "native");
  assert.equal(verdict.reason, "native-nothing-to-read");
  assert.equal(verdict.signals.emptyPages, 2);
});

test("🔴 blank pages inside a readable document do not escalate it", () => {
  const verdict = preflightPdf(
    evidence({ pageTexts: [cleanPage(1), "", cleanPage(3)], unitsWithContent: [0, 2] }),
  );
  assert.equal(verdict.route, "native");
  assert.equal(verdict.reason, "native-read-sufficient");
  assert.equal(verdict.signals.emptyPages, 1);
});

test("scanned pages inside a readable document stay on the cheap page lane", () => {
  const verdict = preflightPdf(
    evidence({ pageTexts: [cleanPage(1), "", cleanPage(3)], unitsWithContent: [0, 1, 2] }),
  );
  assert.equal(verdict.route, "native");
  assert.equal(verdict.reason, "native-page-vision-covers-gaps");
  assert.equal(verdict.signals.thinPages, 1);
});

test("🔴 only the pages the cheap lane cannot pay for reach the specialist, and page-wise", () => {
  const verdict = preflightPdf(
    evidence({
      pageTexts: [cleanPage(1), "", "", "", cleanPage(5)],
      unitsWithContent: [0, 1, 2, 3, 4],
      visionAffordablePages: 1,
    }),
  );
  assert.equal(verdict.route, "vendor");
  assert.equal(verdict.reason, "pages-beyond-vision-budget");
  assert.deepEqual(verdict.pages, [2, 3], "the first thin page is affordable; the rest are not");
});

test("🔴 page-wise escalation is allowed for exactly one cause", () => {
  assert.equal(pageEscalationSafe("pages-beyond-vision-budget"), true);
  for (const reason of ["structure-unavailable", "corrupt-text-layer", "glyph-substitution", "table-not-recovered", "no-text-layer"] as const) {
    assert.equal(pageEscalationSafe(reason), false, `${reason} must never be escalated page-wise`);
  }
});

test("🔴 a rate is not computed over too few words", () => {
  // One scar on a title page is not a broken font. Below the floor the page contributes no scars,
  // so a six-word cover sheet cannot escalate a whole lecture.
  const short = "Chapter One: the ac1on of things";
  assert.ok(short.split(/\s+/).length < MIN_WORDS_FOR_RATE);
  const verdict = preflightPdf(evidence({ pageTexts: [short, cleanPage(2), cleanPage(3)] }));
  assert.equal(verdict.route, "native");
  assert.equal(verdict.signals.scars, 0);
});

test("🔴 the calibrated gap is wide, and this test fails if either edge moves into it", () => {
  // Measured: clean documents at 0.00000, the broken-font class at 0.02535. A constant that
  // drifted up past a tenth of the escalating class, or down to touch zero, stops being a
  // boundary the data shows and becomes a preference.
  assert.ok(MAX_LIGATURE_SCAR_SHARE > 0, "zero would escalate on a single stray token");
  assert.ok(MAX_LIGATURE_SCAR_SHARE < 0.02535 / 10, "the threshold must stay an order of magnitude below the measured damaged class");
  assert.ok(MAX_CORRUPT_CHAR_SHARE > 0);
  assert.ok(MAX_CORRUPT_CHAR_SHARE < 0.01);
});
