// Write the generated study material to disk in Anki-importable form, with a provenance header on every
// artifact. Integrity posture: everything is a DRAFT the student reviews — there is no submit path, and
// each file says so. v0 exports a tab-separated deck (Anki imports this natively via File > Import);
// a one-click .apkg export is the next iteration.

const fs = require("fs");
const path = require("path");

function slugify(s) {
  return String(s || "deck")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60) || "deck";
}

function tsvEscape(s) {
  // tab-separated fields; strip tabs/newlines from fields, keep the text intact otherwise
  return String(s || "").replace(/\t/g, " ").replace(/\r?\n/g, " ").trim();
}

const PROVENANCE_NOTE = "AI-drafted study aid — review before use. Generated by PharmaOrb from your own lecture file. Not a submission; nothing here is turned in for you.";

/**
 * @param {{ outDir: string, sourceName: string, material: any }} args
 * @returns {{ deckDir: string, cardsFile: string, guideFile: string, cardCount: number }}
 */
function writeStudyMaterial(args) {
  const material = args.material;
  const stamp = new Date().toISOString().slice(0, 10);
  const deckDir = path.join(args.outDir, `${stamp}-${slugify(material.deck_title)}`);
  fs.mkdirSync(deckDir, { recursive: true });

  const header = `> ${PROVENANCE_NOTE}\n> Source file: ${args.sourceName}\n> Generated: ${new Date().toISOString()}\n`;

  // Study guide (markdown)
  const guideFile = path.join(deckDir, "study-guide.md");
  const guideParts = [
    `# ${material.deck_title}`,
    "",
    header,
    "",
    material.study_guide_markdown || "_No study guide was generated._",
  ];
  if (material.high_yield && material.high_yield.length) {
    guideParts.push("", "## High-yield", ...material.high_yield.map((h) => `- ${h}`));
  }
  if (material.counseling_points && material.counseling_points.length) {
    guideParts.push("", "## Counseling points", ...material.counseling_points.map((c) => `- ${c}`));
  }
  fs.writeFileSync(guideFile, guideParts.join("\n"), "utf8");

  // Flashcards (tab-separated, Anki-importable). Header directives make the import one step in Anki.
  const cardsFile = path.join(deckDir, "cards.txt");
  const lines = [
    "#separator:tab",
    "#html:false",
    "#columns:Front\tBack\tTags",
    "#tags column:3",
    `#comment:${PROVENANCE_NOTE}`,
  ];
  for (const c of material.cards || []) {
    const tags = (c.tags || []).map((t) => slugify(t)).filter(Boolean).join(" ");
    lines.push([tsvEscape(c.front), tsvEscape(c.back), tags].join("\t"));
  }
  fs.writeFileSync(cardsFile, lines.join("\n") + "\n", "utf8");

  return { deckDir, cardsFile, guideFile, cardCount: (material.cards || []).length };
}

module.exports = { writeStudyMaterial, slugify, PROVENANCE_NOTE };
