/**
 * Which PDFs reach a paid parser, proved end to end through `parseDocument`.
 *
 * 🔴 THE UNIT TESTS IN `lib/pdf/preflight.test.ts` PROVE THE RULE. THIS PROVES THE WIRING, WHICH IS
 * A DIFFERENT THING AND IS WHERE THIS REPOSITORY'S MOST EXPENSIVE DEFECTS HAVE LIVED — a correct
 * decision computed and then not consulted looks exactly like no decision at all. So these run the
 * REAL parser over REAL files and read the route off the `parse_route` record production emits.
 *
 * 🔴 NOTHING HERE REACHES A NETWORK. `MISTRAL_API_KEY` is unset in a test process, so an escalated
 * document's vendor call returns `not-configured` and falls through to the native read — which is
 * also the graceful-degradation path, asserted below: a PDF must never become unreadable because a
 * provider was absent.
 *
 * The corpus is generated by `scripts/make-preflight-corpus.mjs`; regenerate it with
 * `node scripts/make-preflight-corpus.mjs lib/notebooks/fixtures/preflight`.
 */

import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";

import { parseDocument } from "./parse-document";

const CORPUS = join(process.cwd(), "lib/notebooks/fixtures/preflight");
const FIXTURES = join(process.cwd(), "lib/notebooks/fixtures");

interface Route {
  route: "native" | "vendor";
  reason: string;
  signals: Record<string, number | boolean>;
}

/** Run the real parser and pick the routing record out of what it logged. */
async function routeOf(path: string): Promise<{ route: Route; ok: boolean; text: string }> {
  const bytes = new Uint8Array(readFileSync(path));
  const original = console.info;
  let seen: Route | null = null;
  console.info = (line: unknown) => {
    try {
      const parsed = JSON.parse(String(line)) as { event?: string } & Route;
      if (parsed.event === "parse_route") seen = { reason: parsed.reason, route: parsed.route, signals: parsed.signals };
    } catch {
      /* not ours */
    }
  };
  try {
    const outcome = await parseDocument(bytes, path.split("/").pop() ?? "x.pdf", "application/pdf");
    assert.ok(seen, `no parse_route record was emitted for ${path}`);
    return {
      ok: outcome.ok,
      route: seen,
      text: outcome.ok ? outcome.document.text : "",
    };
  } finally {
    console.info = original;
  }
}

const corpusReady = existsSync(join(CORPUS, "clean-lecture.pdf"));

test("🔴 a clean digitally generated lecture never reaches a paid parser", { skip: !corpusReady }, async () => {
  const { ok, route, text } = await routeOf(join(CORPUS, "clean-lecture.pdf"));
  assert.equal(route.route, "native");
  assert.equal(route.reason, "native-read-sufficient");
  assert.equal(ok, true);
  assert.ok(text.length > 1000, "the native read must actually carry the document");
});

test("a dense textbook is still just text", { skip: !corpusReady }, async () => {
  const { route } = await routeOf(join(CORPUS, "dense-textbook.pdf"));
  assert.equal(route.route, "native");
});

test("🔴 a ruled table is recovered for free — the deterministic lattice, not a vendor", { skip: !corpusReady }, async () => {
  const { ok, route, text } = await routeOf(join(CORPUS, "ruled-tables.pdf"));
  assert.equal(route.route, "native", "a grid we can rebuild from its own ruling lines costs nothing");
  assert.equal(route.signals.tablesUnread, 0);
  assert.equal(ok, true);
  assert.ok(text.includes("Column 1"), "the grid's own header must survive into the text");
});

test("a page full of diagrams beside real prose is still a readable document", { skip: !corpusReady }, async () => {
  const { route } = await routeOf(join(CORPUS, "diagram-heavy.pdf"));
  assert.equal(route.route, "native");
});

test("🔴 a broken ligature font escalates, whole, and names why", { skip: !corpusReady }, async () => {
  const { ok, route } = await routeOf(join(CORPUS, "broken-font.pdf"));
  assert.equal(route.route, "vendor");
  assert.equal(route.reason, "glyph-substitution");
  // 🔴 AND THE DOCUMENT IS STILL READABLE. The provider is not configured in a test process, so
  // this is the degradation path: a failed vendor call must leave a usable parse behind.
  assert.equal(ok, true, "a PDF must not become unreadable because a provider was absent");
});

test("🔴 a document that is entirely pixels escalates whole", { skip: !corpusReady }, async () => {
  const { route } = await routeOf(join(CORPUS, "scanned.pdf"));
  assert.equal(route.route, "vendor");
  assert.equal(route.reason, "no-text-layer");
});

test("🔴 scanned pages inside a readable document stay on the cheap page lane", { skip: !corpusReady }, async () => {
  // 🔴 THE KEY IS SET BECAUSE THE ROUTE DEPENDS ON IT, WHICH IS THE POINT. `visionAffordablePages`
  // is read off the real ledger, so "the cheap lane covers these gaps" is only true when the cheap
  // lane exists. Production has `GEMINI_API_KEY`; a test process does not, and asserting the
  // production answer without the production precondition would be asserting a fiction.
  //
  // 🔴 `lookAtFigures` STAYS OFF, so nothing is actually sent anywhere. The key changes what the
  // ROUTER believes it can afford, which is all this test is about.
  const had = process.env.GEMINI_API_KEY;
  process.env.GEMINI_API_KEY = "test-key-not-used-for-any-request";
  try {
    const { route } = await routeOf(join(CORPUS, "mixed-scan.pdf"));
    assert.equal(route.route, "native");
    assert.equal(route.reason, "native-page-vision-covers-gaps");
    assert.equal(route.signals.thinPages, 3);
  } finally {
    if (had === undefined) delete process.env.GEMINI_API_KEY;
    else process.env.GEMINI_API_KEY = had;
  }
});

test("🔴 with no cheap page lane, exactly the unreadable pages escalate — not the document", { skip: !corpusReady }, async () => {
  // The other half of the same rule. With vision unavailable those three pages would simply be
  // lost, so they go to the specialist page-wise — three pages of ten, never ten of ten.
  assert.equal(process.env.GEMINI_API_KEY ?? "", "", "this test assumes an unconfigured vision lane");
  const { ok, route } = await routeOf(join(CORPUS, "mixed-scan.pdf"));
  assert.equal(route.route, "vendor");
  assert.equal(route.reason, "pages-beyond-vision-budget");
  assert.equal(route.signals.thinPages, 3);
  assert.equal(route.signals.pages, 10);
  assert.equal(ok, true, "and the seven readable pages still come back");
});

test("🔴 a blank page is never billed to be told it is blank", async () => {
  const { route } = await routeOf(join(FIXTURES, "blank-page.pdf"));
  assert.equal(route.route, "native");
  assert.equal(route.reason, "native-nothing-to-read");
});

test("🔴 the routing record carries the measurement, not just the verdict", { skip: !corpusReady }, async () => {
  const { route } = await routeOf(join(CORPUS, "broken-font.pdf"));
  // A decision nobody can re-derive is a decision nobody can audit. Every number the rule read has
  // to be in the record beside the answer.
  for (const key of ["pages", "words", "chars", "corruptShare", "scarShare", "tablesUnread", "thinPages"]) {
    assert.ok(key in route.signals, `the parse_route record must carry ${key}`);
  }
  assert.ok(Number(route.signals.scarShare) > 0);
});
