/**
 * XLSX, from a real file to a cell reference that resolves.
 *
 * 🔴 THE STANDING RULE, FOR SPREADSHEETS (owner, 2026-08-11 / 2026-08-12):
 *
 *     real file → parser → DocumentModel → JSON/storage → readStructureEnvelope()
 *              → capabilities → sheet/cell locator RESOLVES
 *
 * Seven structural fields have died at one of those arrows AFTER passing their
 * own parser's tests. So nothing here stops at "the parser produced cells".
 *
 * 🔴 AND THE ASSERTIONS ARE A1 STRINGS, NOT GRID INDICES. A grid coordinate is
 * not a cell reference: a sheet whose data starts at C5 has its first cell at
 * grid (0,0), and a stored-versus-read-back comparison passes whether that is
 * called C5 or A1, because both sides are wrong identically. Only the string
 * catches it — see the `offset-origin` test below.
 *
 * The fixtures are generated by `scripts/make-xlsx-fixtures.py`, and the ones
 * that need a program that actually computes are round-tripped through
 * LibreOffice. See that script for why they are generated rather than collected.
 */

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";

import { projectCells, readStructureEnvelope, structureEnvelope, type DocumentModel } from "@nemesis/shared";

import { parseDocument } from "./parse-document.ts";
import { cellRef } from "./xlsx-model.ts";
import { capabilitiesOfStored, parseQuality } from "@/lib/sources/source-capabilities";

function bytes(name: string): Uint8Array {
  return new Uint8Array(readFileSync(new URL(`./fixtures/xlsx/${name}`, import.meta.url)));
}

/** Parse a fixture and hand back both the parser's model and the read-back one.
 *  Every assertion that matters is made against `after`. */
async function chain(name: string) {
  const outcome = await parseDocument(bytes(name), name, "");
  assert.equal(outcome.ok, true, `${name} must parse`);
  if (!outcome.ok) throw new Error("unreachable");
  const document = outcome.document;
  assert.equal(document.kind, "xlsx");
  const model = document.model;
  assert.ok(model, "a workbook must produce a model");

  const stored = JSON.parse(JSON.stringify(
    structureEnvelope({ model, text: document.text, title: document.title }),
  )) as unknown;
  const read = readStructureEnvelope(stored);
  assert.ok(read && read.shape === "units-blocks", "🔴 the model must survive the envelope");
  if (!read || read.shape !== "units-blocks") throw new Error("unreachable");
  return { after: read.model as DocumentModel, before: model, document, stored };
}

/** The first table block on a given sheet index. */
function tableOn(model: DocumentModel, unit: number) {
  const block = model.blocks.find((b) => b.unit === unit && b.table);
  return block?.table;
}

// ── the one that can ship silently ─────────────────────────────────────────

test("🔴🔴 A SHEET THAT STARTS AT C5 CITES C5, NOT A1", async () => {
  // THE DEFECT THIS SLICE COULD HAVE SHIPPED WITHOUT NOTICING. `offset-origin`
  // declares its used range as C5:D7. Its first cell is at grid (0,0), and every
  // round-trip comparison in this file would pass whether that is reported as C5
  // or A1 — so the assertion has to be the reference string a person would type.
  const { after } = await chain("offset-origin.xlsx");
  const table = tableOn(after, 0);
  assert.ok(table, "the sheet has a grid");
  assert.deepEqual(table.origin, { column: 2, row: 4 }, "the origin survived the boundary");

  const first = table.cells!.find((c) => c.row === 0 && c.column === 0);
  assert.ok(first, "there is a top-left cell");
  assert.equal(cellRef(table, 0, 0), "C5", "🔴 grid (0,0) is C5 — calling it A1 misplaces every citation");
  assert.equal(first.text, "Drug", "and it holds what the sheet holds there");
  assert.equal(cellRef(table, 1, 1), "D6");
  assert.equal(
    table.cells!.find((c) => c.row === 1 && c.column === 1)?.text,
    "500 mg",
    "so 'the dose for Amoxicillin' resolves to a cell a person can open",
  );
});

test("a sheet that does start at A1 stores no origin at all", async () => {
  // The common case stays as quiet in storage as it is in meaning; absent means
  // "starts at the origin", which is what every non-spreadsheet producer means.
  const { after } = await chain("basic.xlsx");
  assert.equal(tableOn(after, 0)?.origin, undefined);
  assert.equal(cellRef(tableOn(after, 0)!, 0, 0), "A1");
});

// ── formula and value are two facts ────────────────────────────────────────

test("🔴 A FORMULA WITH NO CACHED VALUE SURVIVES — the file was written by a program", async () => {
  // openpyxl has no formula engine, so it writes `<f>` and no `<v>` at all.
  // Measured: 4 of 15 cells. A reader that takes values alone loses them
  // entirely and reports the sheet as mostly blank.
  const { after } = await chain("formulas-uncalculated.xlsx");
  const table = tableOn(after, 0)!;
  const withFormula = table.cells!.filter((c) => c.formula);
  assert.ok(withFormula.length >= 4, `expected the formulas to survive, got ${withFormula.length}`);
  const total = table.cells!.find((c) => c.formula?.startsWith("SUM"));
  assert.ok(total, "the SUM is still there");
  assert.equal(total.text, "", "with no cached result, because the file has none — not a fabricated zero");
});

test("🔴 A CACHED VALUE THAT CONTRADICTS ITS FORMULA KEEPS BOTH", async () => {
  // `formulas-stale` has B2 = 9999 while D2 = B2*C2 still caches 2.5, from when
  // B2 was 10 — exactly what a program that edits a sheet without recalculating
  // produces. Choosing either one silently would be this parser deciding which
  // of the file's two claims is true.
  const { after } = await chain("formulas-stale.xlsx");
  const table = tableOn(after, 0)!;
  const at = (ref: string) => table.cells!.find((c) => cellRef(table, c.row, c.column) === ref);

  assert.equal(at("B2")?.text, "9999", "the input is what the file now says it is");
  const d2 = at("D2");
  assert.equal(d2?.formula, "B2*C2", "the question the file asks");
  assert.equal(d2?.text, "2.5", "and the answer the file last recorded — stale, and preserved as stated");
  // The contradiction is the point: 9999 × 0.25 is not 2.5, and both facts are here.
  assert.notEqual(Number(at("B2")!.text) * 0.25, Number(d2!.text));
});

// ── the shapes a workbook actually has ─────────────────────────────────────

test("duplicate column names are kept exactly as written", async () => {
  // A real export had two columns called "Quiz 1". De-duplicating them would
  // silently rename one of a student's marks.
  const { after } = await chain("basic.xlsx");
  const table = tableOn(after, 0)!;
  assert.equal(table.rows[0]!.filter((c) => c === "Quiz 1").length, 2);
});

test("🔴 A HIDDEN SHEET IS STILL HIDDEN, AND STILL PRESENT", async () => {
  // Units are rebuilt field by field at the boundary, where `label` and `size`
  // both died once. Losing `hidden` would put the author's moderation notes in
  // front of the student.
  const { after } = await chain("basic.xlsx");
  const hidden = after.units.filter((u) => u.hidden);
  assert.equal(hidden.length, 1);
  assert.equal(hidden[0]!.label, "Internal");
  assert.ok(
    after.blocks.some((b) => b.unit === hidden[0]!.index),
    "hidden is not deleted — the content is there for a consumer that decides to use it",
  );
});

test("an empty sheet is still a unit, so no locator moves", async () => {
  const { after } = await chain("basic.xlsx");
  assert.equal(after.units.length, 4, "Grades, Notes, Empty Sheet, Internal");
  const empty = after.units.find((u) => u.label === "Empty Sheet")!;
  assert.equal(after.blocks.filter((b) => b.unit === empty.index && b.table).length, 0, "and it holds no grid");
});

test("merged headers survive as spans, and hidden rows and columns are recorded not dropped", async () => {
  const { after } = await chain("merged-hidden.xlsx");
  const table = tableOn(after, 0)!;
  const banner = table.cells!.find((c) => c.text === "Autumn Term");
  assert.equal(banner?.colSpan, 4, "the banner spans the sheet");
  assert.deepEqual(table.hiddenRows, [5], "the hidden row is named, not deleted");
  assert.deepEqual(table.hiddenColumns, [2], "and so is the hidden column");
  // 🔴 The hidden row's content is still reachable. Whether a learner should see
  // it is the consumer's call; only the parser could make it unrecoverable.
  assert.ok(table.cells!.some((c) => c.text === "SECRET"), "the hidden row's content survives");
});

test("a defined table contributes its header count and its name", async () => {
  const { after } = await chain("list-object.xlsx");
  const table = tableOn(after, 0)!;
  assert.equal(table.name, "Inventory", "the workbook's own name for it");
  assert.equal(table.headerRows, 1, "stated by the file, not guessed from appearance");
  assert.deepEqual(table.columns, ["Code", "Name", "Count"]);
});

test("🔴 headerRows STAYS 0 when the file does not say — a top row is not evidence", async () => {
  // Guessing "row 0 is a header" attaches the wrong label to every value beneath
  // it in every file that starts with data.
  const { after } = await chain("basic.xlsx");
  assert.equal(tableOn(after, 0)!.headerRows, 0);
  assert.equal(tableOn(after, 0)!.columns, undefined);
});

test("a date is shown as a date, and the serial it came from is kept", async () => {
  // 2026-03-15 is stored as 46096. Showing "46096" is not an unstyled date, it
  // is a different value — and Nemesis puts dates on a calendar.
  const { after } = await chain("number-formats.xlsx");
  const table = tableOn(after, 0)!;
  const at = (ref: string) => table.cells!.find((c) => cellRef(table, c.row, c.column) === ref);
  assert.equal(at("B2")?.text, "2026-03-15");
  assert.equal(at("B2")?.raw, "46096", "the stored form is kept, so nothing is unrecoverable");
  // A recorded limit, asserted so it cannot drift unnoticed: percentages and
  // currency are NOT rendered. 0.075 is the correct number without decoration.
  assert.equal(at("B3")?.text, "0.075");
  assert.equal(at("B4")?.text, "1234.5");
  assert.equal(at("B5")?.text, "007", "and text that looks numeric stays text");
});

// ── unsupported is not absent ──────────────────────────────────────────────

test("🔴 A CHART MAKES THE WORKBOOK PARTIAL — unsupported is not absent", async () => {
  const outcome = await parseDocument(bytes("with-chart.xlsx"), "with-chart.xlsx", "");
  assert.equal(outcome.ok, true);
  if (!outcome.ok) throw new Error("unreachable");
  assert.ok((outcome.document.coverage.unreadableRegions ?? 0) > 0, "the chart is counted");
  assert.equal(outcome.document.coverage.state, "partial", "so the file cannot report itself fully read");
});

test("a workbook with nothing unsupported reports itself complete", async () => {
  // The calibration case: if everything were `partial`, the flag would mean
  // nothing and nobody would read it.
  const outcome = await parseDocument(bytes("basic.xlsx"), "basic.xlsx", "");
  assert.equal(outcome.ok, true);
  if (!outcome.ok) throw new Error("unreachable");
  assert.equal(outcome.document.coverage.state, "complete");
  assert.equal(outcome.document.coverage.unitKind, "sheet");
  assert.equal(outcome.document.coverage.units, 4, "every sheet is counted, including the empty one");
});

// ── one grid, and what a consumer can do with it ───────────────────────────

test("rows is exactly the projection of cells — never a second copy", async () => {
  for (const name of ["basic.xlsx", "merged-hidden.xlsx", "offset-origin.xlsx"]) {
    const { after } = await chain(name);
    for (const block of after.blocks) {
      if (!block.table?.cells) continue;
      assert.deepEqual(block.table.rows, projectCells(block.table.cells), `${name}: rows must be the projection`);
    }
  }
});

test("a stored workbook reports the capabilities a consumer needs, from the stored bytes", async () => {
  const { stored } = await chain("basic.xlsx");
  const capabilities = capabilitiesOfStored(stored);
  assert.equal(capabilities.text, true, "there is readable text");
  assert.equal(capabilities.tables, true, "and it is a grid, not prose");
  assert.equal(capabilities.mergedCells, true, "with a cell model, so a blank cell means something");
  assert.equal(capabilities.semanticUnits, true);
  assert.equal(capabilities.pageAnchors, true, "so a citation can name its sheet");
  assert.equal(capabilities.hierarchy, true, "the sheet name gives its grid a heading path");
  assert.equal(parseQuality({ capabilities, sourceKind: "xlsx" }), "full");
});

test("the workbook's text is the grids, and it names each sheet", async () => {
  const { document } = await chain("basic.xlsx");
  assert.match(document.text, /Grades/, "the sheet's own tab name reaches the text");
  assert.match(document.text, /Ada/, "and so do the values");
  assert.match(document.text, /\|/, "as a table, not as flattened prose");
});
