/**
 * Filing a new note under the course it is actually about.
 *
 * Owner, 2026-07-31: after a week of lectures everything landed in
 * `Nemesis/Recordings` and `Nemesis/Slides` — a pile, not a semester. A student
 * who records three courses gets one folder holding all of them, sorted by
 * nothing but time.
 *
 * 🔴 THE COURSE LIST IS THE STUDENT'S OWN. It comes from the `course` field on
 * their calendar events and from the folders they already made. There is no
 * table of subject names here and there must never be one: the moment this file
 * knows what "Pharmacology" is, it stops working for the machinist and the law
 * student, and the whole product is field-agnostic by rule. What makes it work
 * is that the student already told the app what they are taking — this only has
 * to notice which of THEIR names a piece of text is talking about.
 *
 * Scope, deliberately: this decides where NEW things are filed. It never moves
 * anything that already exists. A bulk reorganise of notes the student may have
 * arranged by hand is indistinguishable from data loss, and the chat can do it
 * on request through move_library_note if that is really what they want.
 */

import { contentWords, NAME_MIN_WORD } from "./word-overlap.ts";

/**
 * Where things go when no course is a good enough match: one honest Inbox.
 *
 * Owner 2026-08-05: provenance must never be hierarchy. The old fallbacks —
 * `Nemesis/Notes`, `Nemesis/Recordings`, `Nemesis/Slides` — organized material
 * by WHO MADE IT, which is exactly the "Generated by Nemesis" pile the owner
 * banned. An unmatched item now goes to `Inbox`: visibly unsorted, waiting to
 * be classified, instead of filed under a fake taxonomy that reads as done.
 */
export const UNSORTED_FOLDER = "Inbox";

export const FALLBACK_FOLDERS = {
  note: UNSORTED_FOLDER,
  recording: UNSORTED_FOLDER,
  slides: UNSORTED_FOLDER,
} as const;

export type FiledKind = keyof typeof FALLBACK_FOLDERS;

/** What each course folder's subfolder is called, per kind of thing. */
const LEAF: Readonly<Record<FiledKind, string>> = {
  note: "Notes",
  recording: "Lectures",
  slides: "Slides",
};

/** A folder path is one segment per level; these characters would split it.
 *  Exported so every lane that files by course spells the folder identically. */
export function courseFolderSegment(value: string): string {
  return value.trim().replace(/[\\/:]/g, "-").replace(/\s+/g, " ").slice(0, 60);
}
const safeSegment = courseFolderSegment;

/**
 * Course CODES — "2114", "CS50", "MATH-221", "101".
 *
 * 🔴 THE COURSE NUMBER WAS INVISIBLE. contentWords tokenises with a pattern
 * that requires every token to START with a letter, so
 * "PHCY 2114" reduced to the single word {"phcy"} — and so did PHCY 2105, 2109,
 * 2119, 1215 and 1218. Every course in a department scored exactly the same on
 * any text mentioning it, every comparison was a tie, and a tie is a refusal.
 * That is why nothing ever left Inbox: not a missing call, not a failed write,
 * but a matcher that could not tell one PHCY course from another (owner
 * 2026-08-05, production re-acceptance of the Inbox → course rule).
 *
 * A number is the most distinctive part of a course name — it is the part
 * students actually use — so it is counted like any other distinctive token.
 */
/**
 * Separators are word breaks, and the tokenizers do not know that.
 *
 * 🔴 THE SECOND HALF OF THE INVISIBLE-COURSE-NUMBER BUG. #413 fixed the
 * leading-letter rule that hid `2114`. This is the same defect through another
 * door: a hyphenated name is read as ONE enormous word, so
 * `Fall-2026-PHCY-2105-01-Interprofessional-Education-….pdf` — the shape every
 * LMS export and browser download uses — scored ZERO against all six of a
 * student's PHCY courses. Both the number and the department code were inside a
 * token instead of being tokens.
 *
 * Split here, in course filing only, rather than in `contentWords` itself:
 * that function also feeds search ranking and digests, and widening it would
 * change behaviour nobody asked about.
 */
function separated(text: string): string {
  return text.replace(/[-_.]+/g, " ");
}

function courseCodes(text: string): Set<string> {
  const found = separated(text).toLowerCase().match(/[a-z]*\d[a-z0-9]*/g) ?? [];
  return new Set(found);
}

/** Every distinctive token of a course name: its words AND its number. */
export function courseTokens(course: string): Set<string> {
  const tokens = contentWords(separated(course), NAME_MIN_WORD);
  for (const code of courseCodes(course)) tokens.add(code);
  return tokens;
}

/**
 * How strongly a piece of text is about one course.
 *
 * A course name is often several words ("Introduction to Contract Law"), and
 * matching one of them is weak evidence while matching three is strong. So this
 * counts the course's OWN distinctive tokens that appear in the text, rather
 * than answering yes/no — that count is what lets two plausible courses be
 * compared instead of taking whichever was checked first.
 */
export function courseScore(text: string, course: string): number {
  const asked = contentWords(separated(text), NAME_MIN_WORD);
  for (const code of courseCodes(text)) asked.add(code);
  if (asked.size === 0) return 0;
  let hits = 0;
  for (const token of courseTokens(course)) {
    if (asked.has(token)) hits += 1;
  }
  return hits;
}

export interface CourseMatch {
  course: string;
  score: number;
}

/**
 * The one course this text is about, or null when nothing is clear enough.
 *
 * Two rules do the real work, and both exist to make silence the default:
 *
 * - A TIE IS A REFUSAL. Two courses matching equally well means the text does
 *   not distinguish them, and filing it under whichever sorted first would be a
 *   coin toss the student cannot see. Nothing is worse here than confident
 *   misfiling: a note in the wrong course is harder to find than a note in the
 *   obvious pile, because they will not think to look.
 * - ONE SHARED WORD IS NOT ENOUGH when the course name has several. "Advanced
 *   Contract Law" and a transcript that happens to say "advanced" are not a
 *   match. A single-word course name ("Thermodynamics") is exempt, because one
 *   word is all it has.
 */
export function matchCourse(text: string, courses: readonly string[]): CourseMatch | null {
  const scored = courses
    .map((course) => course.trim())
    .filter((course) => course.length > 0)
    .map((course) => {
      const words = courseTokens(course).size;
      const score = courseScore(text, course);
      // Multi-word names need at least two hits; a one-word name needs its word.
      const enough = words <= 1 ? score >= 1 : score >= 2;
      return { course, score: enough ? score : 0 };
    })
    .filter((row) => row.score > 0)
    .sort((a, b) => b.score - a.score);

  const best = scored[0];
  if (!best) return null;
  // A tie means the text did not choose, so neither do we.
  if (scored.length > 1 && scored[1]!.score === best.score) return null;
  return best;
}

/**
 * The folder a new item belongs in.
 *
 * `<Course>/<Lectures|Slides|Notes>` when a course is clear, and today's
 * `Nemesis/...` folder when it is not. The student's existing pile keeps
 * working exactly as it does now; only the recognisable things move out of it.
 */
export function folderForNewItem(
  kind: FiledKind,
  text: string,
  courses: readonly string[],
): string {
  const matched = matchCourse(text, courses);
  if (!matched) return FALLBACK_FOLDERS[kind];
  return `${safeSegment(matched.course)}/${LEAF[kind]}`;
}

/**
 * The Study-page filing rules, built on the same course matching.
 *
 * Study has no folder table — a deck's folder is a `::` prefix inside its own
 * name, and a test's folder is its flat `group_name` string. Until 2026-08-05
 * neither creation lane consulted the student's courses at all: chat decks got
 * whatever bare name the model invented, and tests fell into a group literally
 * named "Generated tests" — the same provenance-as-hierarchy mistake as the
 * Library fallbacks above, on the surface most naturally organized per course.
 */

/**
 * The folder a study item built FROM an attached document should inherit.
 *
 * 🔴 THE ANSWER WAS ALREADY IN THE DATABASE. Owner, 2026-08-06, one turn:
 * "make notes, flashcards and test" over one lecture. The upload lane filed the
 * file under the student's own `Pharmacy` at 15:01:55; the note lane wrote it
 * to `Pharmacy/Lectures` a moment later; and at 15:03:43 the deck lane invented
 * a folder called `Pharmacology` — a name the student never made — because it
 * had only the lecture's words to go on, and a lecture about pharmacogenomics
 * does not contain the word "pharmacy". Three folders, one file, 108 seconds.
 *
 * Where a document lives is a FACT about the student's workspace, not an
 * inference from its prose, which is what makes this the strongest signal here
 * and keeps it field-agnostic: a contracts PDF the student filed under
 * "Contracts" produces a "Contracts" deck without anything knowing what a
 * contract is.
 *
 * Only the TOP segment counts — `Pharmacy/Lectures` is the course, `Lectures`
 * is the shelf. Inbox is by definition the pile for things we could not place,
 * and Nemesis is ours, so neither is a course. Several attachments that
 * disagree are a tie, and a tie is a refusal, exactly as in `matchCourse`.
 */
export function sourceCourseFolder(folderPaths: readonly (string | null | undefined)[]): string {
  const folders = new Set<string>();
  for (const raw of folderPaths) {
    const top = (raw ?? "").split("/").filter(Boolean)[0]?.trim() ?? "";
    if (!top) continue;
    const lowered = top.toLowerCase();
    if (lowered === UNSORTED_FOLDER.toLowerCase() || lowered === "nemesis") continue;
    folders.add(top);
  }
  return folders.size === 1 ? [...folders][0]! : "";
}

/**
 * Did the student themselves name this folder?
 *
 * 🔴 THE TEST THAT SEPARATES A REQUEST FROM AN INVENTION. Owner, 2026-08-06:
 * "a model-provided folder override should only be accepted if that folder name
 * appears in the user's actual message or came from structured UI context.
 * Therefore 'put these in X' can override the source, while an invented
 * 'Pharmacology' cannot."
 *
 * This is a strictly better rule than "does the folder already exist", which was
 * the obvious alternative and is wrong: `Pharmacology` DID already exist as a
 * Study folder — an earlier turn had invented it — so existence launders one
 * invention into permission for the next.
 *
 * Matching is on whole words, case- and separator-insensitive, so "put these in
 * contract law" authorises `Contract Law`. `askText` must be what the student
 * TYPED, with attachment content stripped: a folder name appearing somewhere in
 * an uploaded lecture is the document talking, not the student.
 */
export function folderNamedByStudent(folder: string, askText: string): boolean {
  const wanted = separated(folder).toLowerCase().replace(/\s+/g, " ").trim();
  if (!wanted) return false;
  const said = ` ${separated(askText).toLowerCase().replace(/\s+/g, " ").trim()} `;
  return said.includes(` ${wanted} `)
    // Word-boundary either side, so "law" does not match "lawn" but a trailing
    // comma or full stop still counts as the end of the phrase.
    || new RegExp(`(^|[^a-z0-9])${wanted.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}($|[^a-z0-9])`).test(said);
}

/**
 * Everything that can decide where a new study item goes, in the order it wins.
 *
 * Owner, 2026-08-06 — the precedence, and the reason each rung sits where it
 * does:
 *
 *   1. `selectedFolder` — the student picked it in the UI. Nothing outranks a
 *      deliberate choice they can see on screen.
 *   2. `modelFolder`, but ONLY if `folderNamedByStudent`. This is the student
 *      asking in words; the model is just relaying it. An unvouched model
 *      folder is dropped entirely, never demoted to a guess.
 *   3. (course identity — NOT BUILT. There is no course id anywhere in this
 *      product yet: `calendar_events.course` is free text and nothing else
 *      records a course at all. When a source carries a verified course, it
 *      belongs HERE, above its folder. The gap is left explicit rather than
 *      papered over with a topic guess.)
 *   4. `sourceFolder` — where the document this was built from already lives.
 *   5. nothing — top level, honestly unfiled.
 *
 * 🔴 THE TOPIC MATCHER IS NOT ON THIS LADDER, and that is deliberate. Owner:
 * "if the source has no verified course association, inherit its folder and
 * remain honest. Do not guess a course from the lecture topic." It still runs
 * for items with NO source at all, where there is nothing else to go on — see
 * the callers below.
 */
export interface StudyFilingSignals {
  /** A folder chosen in the UI. */
  selectedFolder?: string;
  /** A folder the model asked for — vouched against `askText` before use. */
  modelFolder?: string;
  /** What the student typed this turn, attachment content stripped. */
  askText?: string;
  /** The folder the source document is already filed in. */
  sourceFolder?: string;
  /** A filed document WAS attached this turn, whether or not its folder was
   *  usable. Separate from `sourceFolder` because "" is ambiguous: it means
   *  both "no attachment" and "an attachment sitting in Inbox", and those two
   *  must end differently. Owner 2026-08-06: "if the source has no verified
   *  course association, inherit its folder and remain honest. Do not guess a
   *  course from the lecture topic." An unplaced document is an answer — the
   *  student has not sorted it yet — so the topic matcher must not overrule it
   *  with a guess. */
  sourceAttached?: boolean;
}

/** The winning folder from the signals above, or "" for none. Pure. */
export function studyFolderFromSignals({ selectedFolder = "", modelFolder = "", askText = "", sourceFolder = "" }: StudyFilingSignals): string {
  const chosen = safeSegment(selectedFolder.trim());
  if (chosen) return chosen;
  const asked = safeSegment(modelFolder.trim());
  if (asked && folderNamedByStudent(modelFolder.trim(), askText)) return asked;
  return safeSegment(sourceFolder.trim());
}

/** True when the signals decide it, so a caller knows not to fall back to the
 *  topic matcher. A document that exists but is unplaced still counts: the
 *  student's own filing said "unsorted", and guessing over it is the thing this
 *  whole ladder exists to stop. */
export function signalsDecided(signals: StudyFilingSignals): boolean {
  return Boolean(studyFolderFromSignals(signals)) || Boolean(signals.sourceAttached) || Boolean(signals.sourceFolder?.trim());
}

/** The deck name a new chat-created deck should get: `<Course>::<name>`.
 *
 *  The folder comes from the signal ladder when anything on it fires. Only a
 *  deck with NO source and no named folder — cards from a conversation, not a
 *  document — falls through to matching the material's words against the
 *  student's courses. A name the model wrote a folder into is respected only
 *  in that last case; when the ladder decides, the invented parent is dropped
 *  and the leaf kept. */
export function deckNameForNewDeck(
  name: string,
  text: string,
  courses: readonly string[],
  signals: StudyFilingSignals = {},
): string {
  const clean = name.trim();
  if (!clean) return clean;
  const decided = studyFolderFromSignals(signals);
  // Keep only the leaf: `Pharmacology::Pharmacogenomics` under a decided
  // `Pharmacy` must become `Pharmacy::Pharmacogenomics`, not a nested folder
  // holding the invented one.
  if (decided) return `${decided}::${clean.split("::").pop()!.trim() || clean}`;
  // A source that exists but sits unplaced ends the ladder honestly.
  if (signalsDecided(signals)) return clean.split("::").pop()!.trim() || clean;
  if (clean.includes("::")) return clean;
  const matched = matchCourse(text, courses);
  if (!matched) return clean;
  return `${safeSegment(matched.course)}::${clean}`;
}

/** The Study group a new test/mindmap belongs in, by the same ladder. Never
 *  "Generated tests". */
export function groupForNewArtifact(text: string, courses: readonly string[], signals: StudyFilingSignals = {}): string {
  const decided = studyFolderFromSignals(signals);
  if (decided) return decided;
  if (signalsDecided(signals)) return "";
  const matched = matchCourse(text, courses);
  return matched ? safeSegment(matched.course) : "";
}

/**
 * The student's courses, from the two places they have already named them.
 *
 * Calendar events carry a `course` field the syllabus import fills in, and the
 * Library's own top-level folders are the ones they made by hand. Both are
 * their words, which is the whole point. De-duplicated case-insensitively,
 * keeping the first spelling seen so the folder matches what they typed.
 */
export function knownCourses(
  calendarCourses: readonly (string | null | undefined)[],
  libraryTopFolders: readonly string[] = [],
): string[] {
  const seen = new Map<string, string>();
  for (const raw of [...calendarCourses, ...libraryTopFolders]) {
    const course = (raw ?? "").trim();
    if (!course) continue;
    // "Nemesis" is ours, not theirs — filing a lecture under it would be a
    // course named after the app.
    if (course.toLowerCase() === "nemesis") continue;
    const key = course.toLowerCase();
    if (!seen.has(key)) seen.set(key, course);
  }
  return [...seen.values()];
}
