// Dynamic "thinking" intent line (DYNAMIC_INTENT=on, default OFF).
//
// WHY: the client shows a FIXED template before every answer ("I'll check what the evidence says
// about X across trusted medical sources, then turn it into a practical answer") — identical every
// time, which reads as canned, not like ChatGPT's per-question reasoning. This replaces it with a
// real, model-written first-person plan specific to THIS question, generated by one cheap
// classify-tier call and emitted early (during the slow retrieval) so it streams in like ChatGPT's.
//
// SCOPE: this line is COSMETIC narration only — it is NOT the answer, is never grounded, never cited,
// and does not affect retrieval or the safety scan. But because it is model text shown to the user,
// it still passes the deterministic forbidden-phrase scan (detectViolations) before it is emitted, so
// it can never surface an unsafe phrase. Fail-safe: any failure (no key, API error, empty, or a line
// that trips the scan) returns null and the client falls back to the existing template.

import { callTool, hasLlmKey, type Tool } from "./llm.ts";
import { modelFor } from "./model-router.ts";
import { detectViolations } from "./safety.ts";

export function dynamicIntentEnabled(): boolean {
  return Deno.env.get("DYNAMIC_INTENT") === "on";
}

const MAX_LEN = 240;

const INTENT_TOOL: Tool = {
  name: "submit_plan_line",
  description: "Submit a one-sentence, first-person plan for how you'll answer the question.",
  parameters: {
    type: "object",
    properties: {
      plan: {
        type: "string",
        description:
          "ONE first-person sentence naming what the question is really asking and what you'll check to answer it. Specific to THIS question — reference the actual drug/condition/comparison. No answer, no verdict, no advice.",
      },
    },
    required: ["plan"],
  },
};

const INTENT_SYSTEM =
  `You write a single first-person sentence describing how you'll approach a health question, shown
to the user while the evidence search runs (like a research assistant thinking out loud). Rules:
- ONE sentence, first person ("I'll ...").
- Name the ACTUAL topic — the specific drug, condition, or comparison in the question.
- Say what you'll look at (e.g. the label, interaction studies, trial results, guidelines), fitting
  the question. Vary naturally; do NOT reuse a fixed template.
- Never answer the question, never give a verdict, dose, or advice. Never claim something is safe.
- Plain, calm, concrete. No hype.`;

/**
 * Generate a per-question first-person plan line. Best-effort: returns null on any failure or if the
 * line trips the forbidden-phrase scan (the client then shows its template). Never throws.
 */
export async function generateIntentLine(question: string, apiKey: string): Promise<string | null> {
  if (!hasLlmKey()) return null;
  try {
    const { input } = await callTool<{ plan?: string }>(
      {
        model: modelFor("classify"),
        max_tokens: 120,
        temperature: 0.5,
        system: INTENT_SYSTEM,
        tools: [INTENT_TOOL],
        messages: [{ role: "user", content: question.slice(0, 500) }],
      },
      "submit_plan_line",
      apiKey,
    );
    let line = String(input.plan ?? "").trim().replace(/\s+/g, " ");
    if (!line) return null;
    if (line.length > MAX_LEN) line = line.slice(0, MAX_LEN).replace(/\s+\S*$/, "") + "…";
    // Cosmetic, but it is model text shown to the user: it must clear the SAME forbidden-phrase scan
    // every answer clears. A tripped line is discarded (null → template fallback), never shown.
    if (detectViolations(line).length > 0) return null;
    return line;
  } catch (e) {
    console.error("dynamic intent line failed; using template:", (e as Error).message);
    return null;
  }
}
