/**
 * Line icons from the Claude Design canvas (gen.py P), 24px grid, round caps.
 * Generated by scratchpad/ios-design/icons-to-tsx — do not hand-edit paths.
 */
import React from 'react';
import Svg, { Circle, Path, Rect } from 'react-native-svg';

const P = {
  notes: () => <><Path d="M5 3h9l5 5v13H5z" /><Path d="M14 3v5h5" /><Path d="M9 13h6" /><Path d="M9 17h4" /></>,
  cards: () => <><Rect x="3" y="7" width="13" height="14" rx="2" /><Path d="M8 3.5h10a2.5 2.5 0 0 1 2.5 2.5v11" /></>,
  spark: () => <><Path d="M12 3.5l1.9 5.1 5.1 1.9-5.1 1.9L12 17.5l-1.9-5.1L5 10.5l5.1-1.9z" /><Path d="M18.5 16l.7 1.8 1.8.7-1.8.7-.7 1.8-.7-1.8-1.8-.7 1.8-.7z" /></>,
  compose: () => <><Path d="M4 20l1-4L16.5 4.5a2.1 2.1 0 0 1 3 3L8 19z" /><Path d="M14.5 6.5l3 3" /></>,
  search: () => <><Circle cx="11" cy="11" r="6.5" /><Path d="M20 20l-4.2-4.2" /></>,
  mic: () => <><Rect x="9" y="3" width="6" height="11" rx="3" /><Path d="M5.5 11a6.5 6.5 0 0 0 13 0" /><Path d="M12 17.5V21" /></>,
  micoff: () => <><Path d="M3 3l18 18" /><Path d="M9 9v2a3 3 0 0 0 5.1 2.1" /><Path d="M15 10V6a3 3 0 0 0-5.7-1.3" /><Path d="M5.5 11a6.5 6.5 0 0 0 10.6 5" /><Path d="M18.5 11a6.4 6.4 0 0 1-.4 2.2" /><Path d="M12 17.5V21" /></>,
  chev_l: () => <><Path d="M15 5l-7 7 7 7" /></>,
  chev_r: () => <><Path d="M9 5l7 7-7 7" /></>,
  chev_d: () => <><Path d="M6 9l6 6 6-6" /></>,
  share: () => <><Path d="M12 3.5v11" /><Path d="M8 7.5l4-4 4 4" /><Path d="M6 12v6.5a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V12" /></>,
  x: () => <><Path d="M6 6l12 12" /><Path d="M18 6L6 18" /></>,
  check: () => <><Path d="M5 12.5l4.5 4.5L19 7.5" /></>,
  play: () => <><Path d="M8 5.5v13l10.5-6.5z" /></>,
  bubble: () => <><Path d="M12 4.5c4.7 0 8.5 3.1 8.5 7s-3.8 7-8.5 7c-1 0-2-.1-2.9-.4L5 19.5l1.2-3.4C4.5 14.8 3.5 13.2 3.5 11.5c0-3.9 3.8-7 8.5-7z" /></>,
  arrow_up: () => <><Path d="M12 19V5" /><Path d="M6 11l6-6 6 6" /></>,
  pause: () => <><Path d="M9 6v12" /><Path d="M15 6v12" /></>,
  calendar: () => <><Rect x="4" y="5" width="16" height="15" rx="2" /><Path d="M4 10h16" /><Path d="M9 3v4" /><Path d="M15 3v4" /></>,
  plus: () => <><Path d="M12 5v14" /><Path d="M5 12h14" /></>,
  bell: () => <><Path d="M6 16v-5a6 6 0 0 1 12 0v5l1.5 2h-15z" /><Path d="M10 20.5a2 2 0 0 0 4 0" /></>,
  sync: () => <><Path d="M20 11a8 8 0 0 0-14.5-4.5L4 8" /><Path d="M4 4v4h4" /><Path d="M4 13a8 8 0 0 0 14.5 4.5L20 16" /><Path d="M20 20v-4h-4" /></>,
  link: () => <><Path d="M10 14a4 4 0 0 0 5.7 0l3-3a4 4 0 0 0-5.7-5.7l-1 1" /><Path d="M14 10a4 4 0 0 0-5.7 0l-3 3a4 4 0 0 0 5.7 5.7l1-1" /></>,
  user: () => <><Circle cx="12" cy="8" r="4" /><Path d="M4.5 20a7.5 7.5 0 0 1 15 0" /></>,
  palette: () => <><Path d="M12 3a9 9 0 1 0 0 18c1.2 0 2-.8 2-1.8 0-1.3-1.2-1.7-1.2-2.9 0-1 .8-1.8 1.8-1.8H17a4 4 0 0 0 4-4C21 6.6 17 3 12 3z" /><Circle cx="7.5" cy="11" r="1" /><Circle cx="10" cy="7" r="1" /><Circle cx="15" cy="7" r="1" /></>,
  help: () => <><Circle cx="12" cy="12" r="9" /><Path d="M9.5 9.5a2.5 2.5 0 1 1 3.5 2.3c-.6.3-1 .9-1 1.6v.6" /><Path d="M12 17.2v.1" /></>,
  logout: () => <><Path d="M14 4h4a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2h-4" /><Path d="M10 16l-4-4 4-4" /><Path d="M6 12h10" /></>,
  wifi_off: () => <><Path d="M3 3l18 18" /><Path d="M8.5 16.5a5 5 0 0 1 7 0" /><Path d="M5 12.5a10 10 0 0 1 4-2.3" /><Path d="M19 12.5a10 10 0 0 0-3.2-2" /><Path d="M12 20h.01" /></>,
  alert: () => <><Circle cx="12" cy="12" r="9" /><Path d="M12 8v5" /><Path d="M12 16.5v.1" /></>,
  aa: () => <><Path d="M3 18l5-12 5 12" /><Path d="M5 14h6" /><Path d="M15 12.5a2.5 2.5 0 0 1 5 0V18" /><Path d="M20 15.5c-3 0-5 .5-5 2 0 .8.7 1.3 1.7 1.3 1.8 0 3.3-1.3 3.3-3.3" /></>,
  image: () => <><Rect x="3.5" y="5" width="17" height="14" rx="2" /><Circle cx="9" cy="10" r="1.6" /><Path d="M20.5 16l-5-5L6 19" /></>,
  at: () => <><Circle cx="12" cy="12" r="3.5" /><Path d="M15.5 12v1.5a2.5 2.5 0 0 0 5 0V12a8.5 8.5 0 1 0-3.4 6.8" /></>,
  comment: () => <><Path d="M5 5h14a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1h-8l-4 3v-3H5a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1z" /></>,
  checklist: () => <><Path d="M4 7l1.5 1.5L8 6" /><Path d="M11 7h9" /><Path d="M4 16l1.5 1.5L8 15" /><Path d="M11 16h9" /></>,
  clock: () => <><Circle cx="12" cy="12" r="8.5" /><Path d="M12 7.5V12l3 2" /></>,
  mail: () => <><Rect x="3.5" y="5.5" width="17" height="13" rx="2" /><Path d="M4 7l8 6 8-6" /></>,
  copy: () => <><Rect x="8" y="8" width="12" height="12" rx="2" /><Path d="M16 8V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2" /></>,
  history: () => <><Path d="M4 12a8 8 0 1 0 2.4-5.7L4 8.5" /><Path d="M4 4v4.5h4.5" /><Path d="M12 8v4l3 2" /></>,
  book: () => <><Path d="M5 4.5h10a3 3 0 0 1 3 3V20H8a3 3 0 0 1-3-3z" /><Path d="M5 17a3 3 0 0 1 3-3h10" /></>,
  star: () => <><Path d="M12 3.5l2.6 5.3 5.9.9-4.3 4.1 1 5.8-5.2-2.7-5.2 2.7 1-5.8-4.3-4.1 5.9-.9z" /></>,
  stop: () => <><Rect x="7" y="7" width="10" height="10" rx="2" /></>,
  globe: () => <><Circle cx="12" cy="12" r="9" /><Path d="M3 12h18" /><Path d="M12 3a14 14 0 0 1 0 18" /><Path d="M12 3a14 14 0 0 0 0 18" /></>,
  hash: () => <><Path d="M9 4L7 20" /><Path d="M17 4l-2 16" /><Path d="M4 9h16" /><Path d="M3.5 15h16" /></>,
  moon: () => <><Path d="M19.5 14.5A8 8 0 0 1 9.5 4.5a8 8 0 1 0 10 10z" /></>,
  minus: () => <><Path d="M6 12h12" /></>,
  bulb: () => <><Path d="M9 18h6" /><Path d="M10 21h4" /><Path d="M12 3a6 6 0 0 0-3.5 10.9c.6.5 1 1.2 1 2V16h5v-.1c0-.8.4-1.5 1-2A6 6 0 0 0 12 3z" /></>,
  folder: () => <><Path d="M3.5 7a2 2 0 0 1 2-2h4l2 2.5h7a2 2 0 0 1 2 2V17a2 2 0 0 1-2 2h-13a2 2 0 0 1-2-2z" /></>,
  clip: () => <><Path d="M20 11.5l-7.8 7.8a5 5 0 0 1-7.1-7.1l8.5-8.5a3.3 3.3 0 0 1 4.7 4.7l-8.5 8.5a1.7 1.7 0 0 1-2.4-2.4l7.8-7.8" /></>,
  file: () => <><Path d="M6 3h8l4 4v14H6z" /><Path d="M14 3v4h4" /></>,
  kbd_down: () => <><Rect x="3" y="3.5" width="18" height="11.5" rx="2" /><Path d="M7 7.5h.01M10.5 7.5h.01M14 7.5h.01M17 7.5h.01M8 11.5h8" /><Path d="M9 18.5l3 2.5 3-2.5" /></>,
  xcirc: () => <><Circle cx="12" cy="12" r="9" /><Path d="M9.2 9.2l5.6 5.6M14.8 9.2l-5.6 5.6" /></>,
  undo: () => <><Path d="M9 14L4 9l5-5" /><Path d="M4 9h10.5a5.5 5.5 0 0 1 0 11H11" /></>,
  bullets: () => <><Circle cx="5" cy="7" r="1" /><Circle cx="5" cy="12" r="1" /><Circle cx="5" cy="17" r="1" /><Path d="M9 7h11M9 12h11M9 17h11" /></>,
  turn: () => <><Path d="M17 3l3 3-3 3" /><Path d="M20 6H9a5 5 0 0 0-5 5" /><Path d="M7 21l-3-3 3-3" /><Path d="M4 18h11a5 5 0 0 0 5-5" /></>,
  // Database view and property icons (hand-drawn in the same 24px, round-cap style; not in gen.py).
  table: () => <><Rect x="3.5" y="5" width="17" height="14" rx="2" /><Path d="M3.5 10h17" /><Path d="M9.5 10v9" /></>,
  board: () => <><Rect x="3.5" y="4.5" width="5" height="15" rx="1.5" /><Rect x="9.5" y="4.5" width="5" height="10" rx="1.5" /><Rect x="15.5" y="4.5" width="5" height="12.5" rx="1.5" /></>,
  timeline: () => <><Path d="M4 6.5h9" /><Path d="M8 12h12" /><Path d="M6 17.5h8" /></>,
  gallery: () => <><Rect x="4" y="4" width="7" height="7" rx="1.5" /><Rect x="13" y="4" width="7" height="7" rx="1.5" /><Rect x="4" y="13" width="7" height="7" rx="1.5" /><Rect x="13" y="13" width="7" height="7" rx="1.5" /></>,
  chart: () => <><Path d="M4 20h16" /><Path d="M7 16.5V11" /><Path d="M12 16.5V6" /><Path d="M17 16.5V9" /></>,
  feed: () => <><Rect x="4" y="3.5" width="16" height="7.5" rx="2" /><Rect x="4" y="13" width="16" height="7.5" rx="2" /><Path d="M7.5 7.25h6" /><Path d="M7.5 16.75h6" /></>,
  pin: () => <><Path d="M12 21s-6.5-5.8-6.5-11a6.5 6.5 0 0 1 13 0c0 5.2-6.5 11-6.5 11z" /><Circle cx="12" cy="10" r="2.3" /></>,
  donut: () => <><Circle cx="12" cy="12" r="8.5" /><Circle cx="12" cy="12" r="3.5" /><Path d="M12 3.5V8.5" /></>,
  trash: () => <><Path d="M4.5 7h15" /><Path d="M9.5 7V4.5h5V7" /><Path d="M6.5 7l1 13h9l1-13" /></>,
  open_out: () => <><Path d="M14 4h6v6" /><Path d="M20 4l-9 9" /><Path d="M18 14v5a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h5" /></>,
  selectprop: () => <><Circle cx="12" cy="12" r="8.5" /><Path d="M8.5 10.5l3.5 3.5 3.5-3.5" /></>,
} as const;

export type NxIconName = keyof typeof P | 'dots' | 'mark';

export function NxIcon({ name, size = 20, color, strokeWidth = 1.6 }: { name: NxIconName; size?: number; color: string; strokeWidth?: number }) {
  if (name === 'dots') {
    return (
      <Svg width={size} height={size} viewBox="0 0 24 24" fill={color}>
        <Circle cx="5.5" cy="12" r="1.5" /><Circle cx="12" cy="12" r="1.5" /><Circle cx="18.5" cy="12" r="1.5" />
      </Svg>
    );
  }
  if (name === 'mark') {
    return (
      <Svg width={size} height={size} viewBox="0 0 28 28" fill={color}>
        <Circle cx="8" cy="9" r="4" /><Circle cx="20" cy="9" r="4" /><Circle cx="14" cy="20" r="4" />
      </Svg>
    );
  }
  const Draw = P[name];
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Draw />
    </Svg>
  );
}
