import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import test from "node:test";

import { inkColors, scopeCss } from "../../scripts/space-scope-css.mjs";

/**
 * 🔴 THE WORKSPACE WEARS OUR DESIGN, NOT THE REFERENCE'S (design/TOKENS.md, owner's ruling 2026-09-11).
 *
 * The layout is a measured copy of another product, so its stylesheet is full of warm greys and of that product's blue
 * accent. Repainting 3,178 colour values by hand would have lost the measurement; instead the build maps them
 * (scripts/space-scope-css.mjs) and a thin layer on top carries type, shape, elevation, focus, motion and the accent.
 * These tests keep both halves honest.
 */
const WEB = path.resolve(__dirname, "../..");
const read = (rel: string) => readFileSync(path.join(WEB, rel), "utf8");

test("🔴 warm greys and the reference's accent come out in our ink, and real colours are left alone", () => {
  const mapped = inkColors(
    ".a{color:#2c2c2b;background:rgba(55,53,47,.08);border-color:#2383e2;fill:rgba(35,131,226,.14)}" +
      ".b{color:#387dc9;background:rgba(139,46,0,.086)}" +
      ".c{box-shadow:0 2px 4px rgba(25,25,25,.08)}" +
      ":root{--c-palUiBlu500:#2383e2}",
  );
  // A warm grey keeps its lightness and loses its warmth.
  assert.match(mapped, /color:rgb\(44,44,44\)/, "an opaque warm grey was not neutralised");
  // A warm tint becomes the ink at the alpha that darkens the ground by the same amount.
  assert.match(mapped, /background:rgba\(16,16,18,0?\.\d+\)/, "a translucent warm tint was not expressed in ink");
  // The reference's accent is a control colour there and ink here, in both themes, through one variable.
  assert.match(mapped, /border-color:var\(--k-ink\)/, "the reference accent stayed blue");
  assert.match(mapped, /fill:color-mix\(in srgb, var\(--k-ink\) 14%, transparent\)/, "a translucent accent wash stayed blue");
  // Tag colours, status colours and artwork are measurements of real hue: they are not touched.
  assert.match(mapped, /color:#387dc9/, "a tag colour was repainted");
  assert.match(mapped, /background:rgba\(139,46,0,\.086\)/, "a tag wash was repainted");
  // Already neutral values (the shadows) stand as measured, and the raw palette is raw material, not a control colour.
  assert.match(mapped, /box-shadow:0 2px 4px rgba\(25,25,25,\.08\)/, "a neutral shadow was rewritten");
  assert.match(mapped, /--c-palUiBlu500:#2383e2/, "the reference's raw palette was repainted");
});

test("🔴 space.css is generated from its two sources, never edited by hand", () => {
  const expected = `/* GENERATED by apps/web/scripts/space-scope-css.mjs from space.src.css and synthesis.src.css. Do not edit. */\n${scopeCss(
    `${inkColors(read("space/styles/space.src.css"))}\n${read("space/styles/synthesis.src.css")}`,
  )}`;
  assert.equal(read("space/styles/space.css"), expected, "space.css is out of step: run `node apps/web/scripts/space-scope-css.mjs`");
});

test("🔴 the accent marks the send button and the learner's own bubble, and nothing else", () => {
  const css = read("space/styles/space.css");
  const wearing: string[] = [];
  for (const [, selector, body] of css.matchAll(/([^{}]+)\{([^}]*)\}/g)) {
    if (/var\(--k-(accent|bubble)\b/.test(body)) wearing.push(selector.trim());
  }
  assert.ok(wearing.length > 0, "nothing wears the accent, so the character has lost its one mark");
  for (const selector of wearing) {
    assert.match(
      selector,
      /send|bubble|:root|nsp-dark-theme/,
      `${selector} wears the accent. The owner's rule (2026-09-11) is that only the send button and the learner's own bubble do.`,
    );
  }
});

test("the design layer carries one ink, both themes, and does not reach for the reference's own names", () => {
  const layer = read("space/styles/synthesis.src.css");
  assert.match(layer, /--k-rgb: 16, 16, 18/, "the light ink changed without a ruling");
  assert.match(layer, /--k-rgb: 237, 237, 238/, "the dark ink changed without a ruling");
  assert.match(layer, /--k-focus: 0 0 0 2px var\(--k-page\), 0 0 0 4px/, "focus stopped being a ring with a gap");
  assert.ok(!/#2783de|#2383e2/.test(layer), "the design layer hard-codes the reference's accent");
});
