"use client";

// A lesson as a short run of screens rather than a page you scroll.
//
// 🔴 THIS IS A REVERSAL AND THE OWNER MADE IT. 2026-09-07: *"books are supposed to be authoritative
// sources... but people think of textbooks like something boring. In contrast, having a course like
// Duolingo is a little bit more engaging for the vast majority of people."* He asked for
// wondering.app's course shape copied one for one as a base to work from.
//
// WHAT THEIR SHAPE ACTUALLY IS, measured inside their own bundle rather than guessed from the
// outside, because from the outside it looks like "shorter lessons" and it is not:
//
//   a lesson opens with a HOOK, a question it has not answered yet, and a line saying why the four
//     minutes are worth spending. Both are their own fields, never prose.
//   a page is ONE idea, and it is small: their own sample lessons run 7 to 102 words a page,
//     averaging 54, across three to five pages. A whole lesson is ~250 words. Ours were 350 to 700.
//   a page heading is a SIGNPOST of two to four words ("The Big Four", "Under the Hood"), not the
//     full sentence our written standard demands for a scrolling page.
//   practice is not a chapter you reach at the end, it is a screen in the run.
//
// WHAT THIS DOES NOT COPY, deliberately: their pictures are generated by an image model and have
// been measured contradicting their own tables (see the canvas teardown), and their prose is not
// grounded in a source anyone can check. Every figure here is the textbook's own, under its own
// licence, with its credit attached, and every sentence came from a real CC BY book. That is the
// one thing we have that they do not, and the deck is only a better way to read it.

import { useEffect, useMemo, useRef, useState } from "react";

import { Check, Figure, Passage } from "./lesson-body";
import { PracticeScreen } from "./lesson-practice";
import { headingId, pagesOf, type Lesson, type LessonPage } from "@/lib/courses/lesson";
import { practiceFrom, type Practice } from "@/lib/courses/practice";

/* ---------------------------------------------------------------- the run */

type Screen =
  | { readonly kind: "hook" }
  | { readonly kind: "page"; readonly page: LessonPage; readonly index: number }
  | { readonly kind: "practice"; readonly practice: Practice };

/**
 * The screens of a lesson, in order.
 *
 * 🔴 A FILL-IN GOES AFTER THE PAGE IT QUOTES, NOT AFTER THE PAGE THAT DEFINED THE WORD. Those look
 * like the same rule and are not, and the difference was visible on the very first run: a question
 * about "anatomy" was placed after page one, because page one is where the word is marked, while the
 * sentence it blanked out came from page six. The learner was asked to complete a sentence they had
 * not read yet, which both spoils the ending and cannot be answered from anything on screen.
 * `practiceFrom` reports the page each question was drawn from, and that is where it goes.
 *
 * At most one exercise per page. A lesson that defines four words on one screen would otherwise stop
 * the reader four times in a row, which is where a course starts feeling like homework. Anything
 * with no page of its own (Match Pairs spans the lesson) closes the run.
 */
export function screensOf(lesson: Lesson): Screen[] {
  const pages = pagesOf(lesson);
  const deck = practiceFrom(lesson);
  const placed = new Set<Practice>();

  const out: Screen[] = [];
  if (lesson.hook || lesson.meaning) out.push({ kind: "hook" });

  pages.forEach((page, index) => {
    out.push({ kind: "page", page, index });
    const next = deck.find((p) => !placed.has(p) && p.kind !== "match" && p.fromPage === index);
    if (next) {
      placed.add(next);
      out.push({ kind: "practice", practice: next });
    }
  });

  for (const p of deck) if (!placed.has(p)) out.push({ kind: "practice", practice: p });
  return out;
}

/* ---------------------------------------------------------------- furniture */

function Progress({ at, of: total }: { at: number; of: number }) {
  return (
    <div aria-hidden className="flex items-center gap-[4px]">
      {Array.from({ length: total }, (_, i) => (
        <span
          className="h-[3px] flex-1 rounded-full transition-colors duration-200"
          key={i}
          style={{ background: i <= at ? "var(--ui-action)" : "var(--ui-bg-tertiary)" }}
        />
      ))}
    </div>
  );
}

/**
 * The question the lesson has not answered yet.
 *
 * 🔴 THE HOOK IS A RHETORICAL QUESTION AND THAT IS THE POINT. The written standard bans them in the
 * passage, and it is right to: a lesson that keeps asking "so what holds them together?" is
 * performing. Asked ONCE, on its own screen, before any teaching, it is not a mannerism, it is the
 * reason to read on. Keeping it in its own field is what stops it leaking back into the prose.
 */
function Hook({ lesson, objectives }: { lesson: Lesson; objectives: readonly string[] }) {
  return (
    <div className="flex flex-col gap-[22px]">
      <div className="flex flex-col gap-[16px] rounded-[16px] border border-(--ui-stroke-tertiary) bg-(--ui-bg-quaternary) px-[24px] py-[26px]">
        {lesson.hook ? (
          <p className="m-0 text-[22px] font-semibold leading-[1.35] tracking-[-0.01em] text-(--ui-text-primary)">
            {lesson.hook}
          </p>
        ) : null}
        {lesson.meaning ? (
          <p className="m-0 text-[15px] leading-[1.65] text-(--course-quiet)">{lesson.meaning}</p>
        ) : null}
      </div>
      {/* 🔴 THE OBJECTIVES BELONG ON THE FIRST SCREEN ONLY. The reader used to draw them above the
          lesson, which in a deck means above EVERY screen: eleven repeats of a card taller than the
          page under it, so the top third of the run was the same list eleven times. They are what
          you agree to before you start, not a heading. */}
      {objectives.length > 0 ? (
        <div className="flex flex-col gap-[8px]">
          <div className="text-[12px] uppercase tracking-[0.06em] text-(--course-meta)">By the end of this you can</div>
          <ul className="m-0 flex list-none flex-col gap-[6px] p-0">
            {objectives.map((item) => (
              <li className="flex gap-[10px] text-[14px] leading-[1.6] text-(--course-quiet)" key={item}>
                <span aria-hidden className="text-(--course-meta)">&mdash;</span>
                {item}
              </li>
            ))}
          </ul>
        </div>
      ) : null}
    </div>
  );
}

function Page({ page, lesson, id }: { page: LessonPage; lesson: Lesson; id: string }) {
  return (
    <div className="flex flex-col gap-[18px]">
      {page.heading ? (
        <h2 className="m-0 text-[13px] font-semibold uppercase tracking-[0.07em] text-(--course-meta)" id={id}>
          {page.heading}
        </h2>
      ) : null}
      {page.blocks.map((block, i) => {
        switch (block.kind) {
          case "text":
            return <Passage key={i} lesson={lesson} text={block.text} />;
          case "figure":
            return <Figure block={block} key={i} lesson={lesson} />;
          case "check":
            return <Check block={block} key={i} />;
          case "heading":
            return null;
        }
      })}
    </div>
  );
}

/* ---------------------------------------------------------------- the deck */

/** Which screen shows page `n`, so the outline rail can jump into the middle of a run. */
export function screenOfPage(screens: readonly Screen[], page: number): number {
  const at = screens.findIndex((s) => s.kind === "page" && s.index === page);
  return at === -1 ? 0 : at;
}

export function LessonDeck({
  lesson,
  objectives,
  onFinish,
  onScrollInstead,
  jumpTo,
  sectionOrdinal,
}: {
  lesson: Lesson;
  objectives: readonly string[];
  onFinish: () => void;
  onScrollInstead: () => void;
  /** A page the outline rail asked for, and a token that changes on every ask so the same row
   *  clicked twice still moves. */
  jumpTo: { readonly page: number; readonly token: number } | null;
  sectionOrdinal: number;
}) {
  const screens = useMemo(() => screensOf(lesson), [lesson]);
  const [at, setAt] = useState(0);
  const [answered, setAnswered] = useState<ReadonlySet<number>>(() => new Set());
  const top = useRef<HTMLDivElement>(null);

  // 🔴 A NEW SCREEN THAT ARRIVES HALFWAY DOWN IS READ HALFWAY DOWN. The reading column keeps its
  // scroll position across a React state change, so a long page followed by a short one leaves the
  // learner staring at white space with the text above the fold. `at` is in the dependency list
  // rather than the screen's identity, so pressing Continue twice on identical screens still moves.
  useEffect(() => {
    const column = top.current?.closest<HTMLElement>(".course-reading-column");
    if (column && column.scrollTop > 0) column.scrollTop = 0;
  }, [at]);

  // Starting a different section restarts the run, which is otherwise left mid-lesson on the screen
  // number of the section you came from, with the previous lesson's answers still marked.
  useEffect(() => {
    setAt(0);
    setAnswered(new Set());
  }, [lesson]);

  // 🔴 THE RAIL HAS TO REACH INTO A DECK, and before this it silently could not: every row called
  // `scrollToHeading`, which finds an element by id, and in the deck the other pages are not in the
  // document at all. Clicking a heading did nothing and looked like a broken link.
  useEffect(() => {
    if (jumpTo) setAt(screenOfPage(screens, jumpTo.page));
  }, [jumpTo, screens]);

  const screen = screens[at];
  if (!screen) return null;
  const last = at === screens.length - 1;
  const held = screen.kind === "practice" && !answered.has(at);

  return (
    <div className="flex min-h-[calc(100vh-260px)] flex-col gap-[24px]" ref={top}>
      <Progress at={at} of={screens.length} />

      {/* 🔴 THE FOOTER SITS AT THE BOTTOM OF THE COLUMN, NOT UNDER THE TEXT. A 28-word closing page
          otherwise put Continue a third of the way up a tall empty column, which reads as a page
          that failed to load rather than a page that is short. The screen grows to fill what is
          left of the column and the controls stay where the hand expects them. */}
      <div className="flex min-h-[min(420px,50vh)] flex-1 flex-col">
        {screen.kind === "hook" ? <Hook lesson={lesson} objectives={objectives} /> : null}
        {screen.kind === "page" ? (
          <Page id={headingId(sectionOrdinal, screen.index)} lesson={lesson} page={screen.page} />
        ) : null}
        {screen.kind === "practice" ? (
          // 🔴 CONTINUE IS HELD UNTIL THE QUESTION IS ANSWERED, and the answer is REMEMBERED PER
          // SCREEN rather than reset on every render. A single `held` flag looked identical until
          // you pressed Back: returning to a question you had already answered locked the button
          // again with no way to unlock it except answering it a second time.
          <PracticeScreen
            key={at}
            onAnswered={() => setAnswered((prev) => new Set(prev).add(at))}
            practice={screen.practice}
          />
        ) : null}
      </div>

      <div className="mt-auto flex items-center justify-between gap-[16px] border-t border-(--ui-stroke-tertiary) pt-[18px]">
        <button
          className="cursor-pointer rounded-[8px] border-0 bg-transparent px-0 text-[13px] text-(--course-meta) transition-colors duration-[90ms] hover:text-(--ui-text-primary)"
          onClick={onScrollInstead}
          type="button"
        >
          Read it as one page
        </button>
        <div className="flex items-center gap-[10px]">
          {at > 0 ? (
            <button
              className="cursor-pointer rounded-[10px] border border-(--ui-stroke-tertiary) bg-transparent px-[16px] py-[9px] text-[14px] font-medium text-(--course-quiet) transition-colors duration-[90ms] hover:bg-(--ui-bg-quaternary)"
              onClick={() => setAt((v) => Math.max(0, v - 1))}
              type="button"
            >
              Back
            </button>
          ) : null}
          <button
            className="cursor-pointer rounded-[10px] border-0 px-[22px] py-[10px] text-[14px] font-semibold text-(--ui-action-glyph) transition-opacity duration-[90ms] disabled:cursor-not-allowed disabled:opacity-40"
            disabled={held}
            onClick={() => (last ? onFinish() : setAt((v) => v + 1))}
            style={{ background: "var(--ui-action)" }}
            type="button"
          >
            {last ? "Finish" : "Continue"}
          </button>
        </div>
      </div>
    </div>
  );
}
