-- 20260824T20 — a deck can be handed to a classmate, and taken back.
--
-- Owner's build order, workstream G: *"A deck or a course gets a link. Someone opens it,
-- studies it, and can copy it into their own library. That is the cheapest growth a
-- learning app gets: one student in a class can mean the class."*
--
-- 🔴🔴🔴 THIS TABLE IS THE ONLY THING THAT MAKES ANY PRIVATE ROW PUBLIC, WHICH IS WHY IT
-- IS SO SMALL. Sharing is publishing: the moment a row exists here, anyone holding the
-- token can read that deck's cards without signing in. So the design is a single
-- explicit, revocable grant per deck, and NOTHING about the sharer travels with it — no
-- name, no email, no user id in the payload the reader gets. A share says "here are some
-- cards", never "here is who made them".
--
-- 🔴🔴 THE TOKEN IS THE SECRET AND IT IS GENERATED BY THE DATABASE. A client-chosen token
-- is a client-chosen guess: an id derived from the deck, the title, or a counter is
-- enumerable, and enumerable means every shared deck on the platform is readable by
-- counting. `gen_random_uuid()` twice gives 256 bits, which is not guessable and not worth
-- anyone's time to try.
--
-- 🔴 REVOKING IS A DELETE, NOT A FLAG. A `revoked boolean` invites a reader that forgets
-- to check it; a missing row cannot be read by any query anyone will ever write. The cost
-- is that re-sharing mints a new link, which is the correct behaviour anyway — a revoked
-- link coming back to life is exactly what a person revoking did not want.
--
-- 🔴 NO ROW LEVEL SECURITY FOR READERS, BECAUSE READERS ARE NOT LOGGED IN. The public read
-- happens in one server route holding the service role (`app/api/shared/[token]/route.ts`),
-- which is the single auditable place where private rows become public. Learners can only
-- ever create and delete their OWN shares, which is what the policy below covers.

create table if not exists public.deck_shares (
  -- The link. Two uuids concatenated without dashes: unguessable, and short enough that a
  -- learner can paste it into a group chat without it wrapping.
  token text primary key default replace(gen_random_uuid()::text, '-', '') || replace(gen_random_uuid()::text, '-', ''),

  deck_id uuid not null references public.study_decks(id) on delete cascade,

  -- 🔴 WHO SHARED IT, FOR REVOCATION ONLY. It is never sent to a reader. The route selects
  -- the cards and the deck name and nothing else.
  shared_by uuid not null references auth.users(id) on delete cascade,

  created_at timestamptz not null default now(),

  -- One live link per deck. Sharing twice should hand out the same link rather than
  -- accumulating a trail of live tokens nobody remembers granting.
  unique (deck_id)
);

comment on table public.deck_shares is
  'One revocable public link per shared flashcard deck. The only path by which a private study_decks row becomes readable without signing in.';

alter table public.deck_shares enable row level security;

-- 🔴 OWNER-ONLY, AND DELIBERATELY NOT A `for all` OVER EVERYTHING. A learner may create and
-- delete their own shares. Nobody reads this table through RLS at all: the public read is
-- the service-role route, and a learner listing "which of my decks are shared" is a select
-- over their own rows, which `shared_by = auth.uid()` covers.
drop policy if exists deck_shares_owner on public.deck_shares;
create policy deck_shares_owner on public.deck_shares
  for all using (auth.uid() = shared_by) with check (auth.uid() = shared_by);

create index if not exists deck_shares_owner_idx on public.deck_shares (shared_by, created_at desc);
