-- Notebook deliverables (owner ask 2026-07-20): Flashcards / Test / Slides
-- generated by the engine from a notebook's sources, listed under the
-- notebook's Outputs toggle. Owner-only RLS, same posture as
-- chat_recording_artifacts (20260720195715).

create table if not exists public.notebook_outputs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  notebook_id uuid not null references public.notebooks (id) on delete cascade,
  kind text not null check (kind in ('flashcards', 'test', 'slides')),
  title text not null default '',
  content text not null default '',
  status text not null default 'pending' check (status in ('pending', 'ready', 'failed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists notebook_outputs_notebook_idx
  on public.notebook_outputs (notebook_id, created_at desc);

alter table public.notebook_outputs enable row level security;

drop policy if exists notebook_outputs_owner_select on public.notebook_outputs;
create policy notebook_outputs_owner_select on public.notebook_outputs
  for select to authenticated using (user_id = auth.uid());

drop policy if exists notebook_outputs_owner_insert on public.notebook_outputs;
create policy notebook_outputs_owner_insert on public.notebook_outputs
  for insert to authenticated with check (user_id = auth.uid());

drop policy if exists notebook_outputs_owner_update on public.notebook_outputs;
create policy notebook_outputs_owner_update on public.notebook_outputs
  for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists notebook_outputs_owner_delete on public.notebook_outputs;
create policy notebook_outputs_owner_delete on public.notebook_outputs
  for delete to authenticated using (user_id = auth.uid());

revoke all on public.notebook_outputs from anon, authenticated;
grant select, insert, update, delete on public.notebook_outputs to authenticated;
