// The twenty designs.
//
// 🔴 A DESIGN IS A COMPOSITION, NOT A COLOURWAY. This file replaced an earlier deck-themes.ts
// that varied only palette — the owner's verdict was that every deck still looked the same,
// and they were right. Each entry below picks its own cover construction, its own way of
// setting a list, its own section break, its own way of showing a number and a quotation. Two
// designs sharing a cover archetype never share the body treatment.
//
// Fonts come from SAFE_FONTS: nothing is embedded in a .pptx, so a font the machine lacks is a
// design that silently becomes a different one.
//
// Colour roles, so a composition can place text without guessing:
//   paper/ink/soft/muted  the page and its three text weights
//   accent/accentInk      the brand colour, and what is legible ON it
//   deep/deepInk/deepSoft the full-bleed field a cover or section is built on

import type { DeckDesign } from "./deck-compose";

export const SAFE_FONTS = [
  "Arial",
  "Calibri",
  "Cambria",
  "Candara",
  "Consolas",
  "Constantia",
  "Corbel",
  "Courier New",
  "Georgia",
  "Tahoma",
  "Times New Roman",
  "Trebuchet MS",
  "Verdana",
] as const;

/** The house design, and the fallback whenever a stored id no longer exists. */
const HOUSE: DeckDesign = {
  accent: "c8102e",
  accentInk: "fff5f5",
  blurb: "Crimson block down the edge, points set as cards. The house look.",
  body: "cards",
  cover: "band-left",
  deep: "17151a",
  deepInk: "f7f4f4",
  deepSoft: "a49ea6",
  fonts: { body: "Calibri", display: "Georgia" },
  id: "studio",
  ink: "17151a",
  muted: "8b8590",
  name: "Studio",
  paper: "faf8f7",
  quote: "mark",
  section: "band",
  soft: "494650",
  stat: "panel",
};

export const DECK_DESIGNS: readonly DeckDesign[] = [
  HOUSE,
  {
    accent: "2f5fd0",
    accentInk: "f4f7ff",
    blurb: "A navy panel holds the subtitle; points arrive numbered, one rule apart.",
    body: "numbered",
    cover: "panel-right",
    deep: "0d1b33",
    deepInk: "f2f6fc",
    deepSoft: "9db0cd",
    fonts: { body: "Calibri", display: "Cambria" },
    id: "meridian",
    ink: "111a2b",
    muted: "7c8698",
    name: "Meridian",
    paper: "ffffff",
    quote: "rule",
    section: "split",
    soft: "3d4759",
    stat: "rule",
  },
  {
    accent: "c1121f",
    accentInk: "fff4f2",
    blurb: "Newspaper: a ribbon across the cover, headline banners, hard black rules.",
    body: "banner",
    cover: "ribbon",
    deep: "141414",
    deepInk: "fbfaf8",
    deepSoft: "a8a49e",
    fonts: { body: "Arial", display: "Georgia" },
    id: "bulletin",
    ink: "141414",
    muted: "7d7a75",
    name: "Bulletin",
    paper: "fbfaf6",
    quote: "band",
    section: "band",
    soft: "3f3d3a",
    stat: "block",
  },
  {
    accent: "b3401f",
    accentInk: "fdf6f1",
    blurb: "A thin frame, centred type and a lot of air. Quiet, editorial, printed.",
    body: "boxed",
    cover: "frame",
    deep: "241f1b",
    deepInk: "f7f2ec",
    deepSoft: "b3aaa0",
    fonts: { body: "Corbel", display: "Constantia" },
    id: "kyoto",
    ink: "231f1c",
    muted: "8a8178",
    name: "Kyoto",
    paper: "f7f4ee",
    quote: "rule",
    section: "rule",
    soft: "4a443d",
    stat: "rule",
  },
  {
    accent: "c79a2e",
    accentInk: "1d2318",
    blurb: "A giant numeral behind the title, and body copy that hangs off a full rule.",
    body: "hanging-rule",
    cover: "numeral",
    deep: "12241a",
    deepInk: "f2f7f2",
    deepSoft: "a3b7a6",
    fonts: { body: "Corbel", display: "Cambria" },
    id: "atlas",
    ink: "14261c",
    muted: "7f8a80",
    name: "Atlas",
    paper: "f6f8f5",
    quote: "rule",
    section: "solid-numeral",
    soft: "3c4a41",
    stat: "rule",
  },
  {
    accent: "0b63e5",
    accentInk: "f2f7ff",
    blurb: "Two blocks in opposite corners; every point becomes a pill you can scan.",
    body: "chips",
    cover: "corner-blocks",
    deep: "0a1929",
    deepInk: "f3f7fb",
    deepSoft: "9cb0c4",
    fonts: { body: "Tahoma", display: "Trebuchet MS" },
    id: "signal",
    ink: "10171f",
    muted: "78828d",
    name: "Signal",
    paper: "ffffff",
    quote: "panel",
    section: "band",
    soft: "3a434e",
    stat: "circle",
  },
  {
    accent: "d2570d",
    accentInk: "1c1310",
    blurb: "A burning arc in the corner, cards for the content, a slab beside the number.",
    body: "cards",
    cover: "arc-corner",
    deep: "17120f",
    deepInk: "f8f3ee",
    deepSoft: "aca093",
    fonts: { body: "Calibri", display: "Georgia" },
    id: "ember",
    ink: "1d1a17",
    muted: "857d74",
    name: "Ember",
    paper: "fbf8f4",
    quote: "mark",
    section: "band",
    soft: "46403a",
    stat: "block",
  },
  {
    accent: "e02020",
    accentInk: "ffffff",
    blurb: "Three bars, primary colour, numbered rows. Bauhaus with the volume up.",
    body: "numbered",
    cover: "stack-bars",
    deep: "111111",
    deepInk: "ffffff",
    deepSoft: "a8a8a8",
    fonts: { body: "Arial", display: "Arial" },
    id: "primary",
    ink: "111111",
    muted: "767676",
    name: "Primary",
    paper: "ffffff",
    quote: "panel",
    section: "split",
    soft: "343434",
    stat: "block",
  },
  {
    accent: "9a6b3f",
    accentInk: "fdf9f1",
    blurb: "Centred title between hairlines, indented copy. Reads like a printed essay.",
    body: "hanging-rule",
    cover: "editorial",
    deep: "241c12",
    deepInk: "f8f2e6",
    deepSoft: "bcae97",
    fonts: { body: "Candara", display: "Georgia" },
    id: "linen",
    ink: "2c2318",
    muted: "8b7f6c",
    name: "Linen",
    paper: "faf6ee",
    quote: "rule",
    section: "rule",
    soft: "4a4032",
    stat: "rule",
  },
  {
    accent: "1a4fd6",
    accentInk: "f4f7ff",
    blurb: "Half the cover is colour; content sits in two columns either side of a rule.",
    body: "two-col-rule",
    cover: "half-split",
    deep: "0e1f4d",
    deepInk: "f3f6fd",
    deepSoft: "a3b2d4",
    fonts: { body: "Calibri", display: "Cambria" },
    id: "cobalt",
    ink: "0f1729",
    muted: "79839a",
    name: "Cobalt",
    paper: "ffffff",
    quote: "band",
    section: "band",
    soft: "39435a",
    stat: "panel",
  },
  {
    accent: "c07a17",
    accentInk: "1a1815",
    blurb: "A dotted field, a dark rail beside every list. Industrial and calm.",
    body: "rail",
    cover: "grid-dots",
    deep: "1c1a17",
    deepInk: "f5f3ef",
    deepSoft: "a8a29a",
    fonts: { body: "Corbel", display: "Cambria" },
    id: "slate",
    ink: "1c1a17",
    muted: "857f77",
    name: "Slate",
    paper: "f5f4f2",
    quote: "rule",
    section: "split",
    soft: "46423c",
    stat: "rule",
  },
  {
    accent: "b2477a",
    accentInk: "fff5fa",
    blurb: "A rising circle, cards in plum, a ring around every number.",
    body: "cards",
    cover: "circle",
    deep: "22132a",
    deepInk: "f9f2f7",
    deepSoft: "b8a3b8",
    fonts: { body: "Calibri", display: "Cambria" },
    id: "orchid",
    ink: "241428",
    muted: "8a7c88",
    name: "Orchid",
    paper: "fdf7fa",
    quote: "mark",
    section: "solid-numeral",
    soft: "483f4c",
    stat: "circle",
  },
  {
    accent: "9fe870",
    accentInk: "0c1108",
    blurb: "Black field, a lime band under the title, everything inside a hairline box.",
    body: "boxed",
    cover: "band-bottom",
    deep: "0b0d0c",
    deepInk: "f4f7f4",
    deepSoft: "97a094",
    fonts: { body: "Consolas", display: "Consolas" },
    id: "terminal",
    ink: "10120f",
    muted: "7f857c",
    name: "Terminal",
    paper: "f4f6f3",
    quote: "rule",
    section: "rule",
    soft: "3a3e38",
    stat: "block",
  },
  {
    accent: "0f7d86",
    accentInk: "f0fafb",
    blurb: "A diagonal cut across the cover; titles ride a dark panel above the content.",
    body: "panel-title",
    cover: "split-diagonal",
    deep: "07202e",
    deepInk: "eff8f9",
    deepSoft: "9ab6bd",
    fonts: { body: "Corbel", display: "Georgia" },
    id: "harbor",
    ink: "07242c",
    muted: "738288",
    name: "Harbor",
    paper: "f3f9fa",
    quote: "band",
    section: "band",
    soft: "35474c",
    stat: "panel",
  },
  {
    accent: "b4562a",
    accentInk: "fdf6ef",
    blurb: "Sandstone block, sienna rules, copy indented off a long line.",
    body: "hanging-rule",
    cover: "band-left",
    deep: "241a12",
    deepInk: "f9f2e8",
    deepSoft: "bfae98",
    fonts: { body: "Tahoma", display: "Constantia" },
    id: "sandstone",
    ink: "2a2119",
    muted: "8b7f6f",
    name: "Sandstone",
    paper: "f8f2e8",
    quote: "mark",
    section: "rule",
    soft: "4c4237",
    stat: "rule",
  },
  {
    accent: "6a5ae0",
    accentInk: "f6f4ff",
    blurb: "The one that glows: painted light on the cover, violet cards inside.",
    art: {
      closing: {
        base: "15112e",
        glows: [{ color: "6a5ae0", cx: 0.5, cy: 1.06, r: 0.8, strength: 0.45 }],
        grain: 0.4,
        vignette: 0.42,
      },
      cover: {
        base: "15112e",
        glows: [
          { color: "3b2fa0", cx: 0.16, cy: 0.2, r: 0.6, strength: 0.55 },
          { color: "8c6ce8", cx: 0.88, cy: 0.85, r: 0.58, strength: 0.5 },
        ],
        grain: 0.45,
        vignette: 0.36,
      },
      section: {
        base: "f1eefb",
        glows: [{ color: "ffffff", cx: 0.2, cy: 0.18, r: 0.6, strength: 0.6 }],
        grain: 0.28,
        ramp: { angle: 118, to: "ded7f4" },
      },
    },
    body: "cards",
    cover: "art-glow",
    deep: "15112e",
    deepInk: "f4f1fd",
    deepSoft: "aca4cd",
    fonts: { body: "Corbel", display: "Cambria" },
    id: "aurora",
    ink: "1b1633",
    muted: "817a9a",
    name: "Aurora",
    paper: "f8f6fd",
    quote: "panel",
    section: "art",
    soft: "413c5c",
    stat: "circle",
  },
  {
    accent: "d90429",
    accentInk: "ffffff",
    blurb: "Broadsheet: serif headlines, two columns, one red rule doing all the shouting.",
    body: "two-col-rule",
    cover: "ribbon",
    deep: "1a1a1a",
    deepInk: "fafafa",
    deepSoft: "a5a5a5",
    fonts: { body: "Arial", display: "Times New Roman" },
    id: "press",
    ink: "16161a",
    muted: "76767c",
    name: "Press",
    paper: "fdfdfb",
    quote: "rule",
    section: "band",
    soft: "3a3a40",
    stat: "rule",
  },
  {
    accent: "2f7d52",
    accentInk: "f3faf5",
    blurb: "A field of green dots, points as chips, a ring around the headline number.",
    body: "chips",
    cover: "grid-dots",
    deep: "0d2119",
    deepInk: "f0f7f2",
    deepSoft: "a2bbaa",
    fonts: { body: "Calibri", display: "Georgia" },
    id: "fern",
    ink: "10261a",
    muted: "7b8a80",
    name: "Fern",
    paper: "f4f8f4",
    quote: "rule",
    section: "split",
    soft: "39473d",
    stat: "circle",
  },
  {
    accent: "c2600f",
    accentInk: "fff8ef",
    blurb: "A light cover for once: gold band along the bottom, brown ink above it.",
    body: "plain",
    cover: "band-bottom",
    deep: "f3c98a",
    deepInk: "2b2115",
    deepSoft: "6a5334",
    fonts: { body: "Calibri", display: "Georgia" },
    id: "dawn",
    ink: "2b2115",
    muted: "8a7a63",
    name: "Dawn",
    paper: "fffaf2",
    quote: "mark",
    section: "band",
    soft: "4e4335",
    stat: "rule",
  },
  {
    accent: "e8e8e8",
    accentInk: "111111",
    blurb: "Pure black and white. A numeral, a rail, and nothing it does not need.",
    body: "rail",
    cover: "numeral",
    deep: "000000",
    deepInk: "ffffff",
    deepSoft: "9e9e9e",
    fonts: { body: "Trebuchet MS", display: "Trebuchet MS" },
    id: "onyx",
    ink: "000000",
    muted: "757575",
    name: "Onyx",
    paper: "ffffff",
    quote: "band",
    section: "solid-numeral",
    soft: "2e2e2e",
    stat: "block",
  },
];

export const DEFAULT_DECK_DESIGN = HOUSE.id;

/** Look one up by id, falling back to the house design — a stored id must never break a build. */
export function deckDesign(id: string | null | undefined): DeckDesign {
  return DECK_DESIGNS.find((d) => d.id === id) ?? HOUSE;
}
