// The twenty designs.
//
// 🔴 A DESIGN IS A COMPOSITION, NOT A COLOURWAY. This file replaced an earlier deck-themes.ts
// that varied only palette — the owner's verdict was that every deck still looked the same,
// and they were right. Each entry below picks its own cover construction, its own way of
// setting a list, its own section break, its own way of showing a number and a quotation. Two
// designs sharing a cover archetype never share the body treatment.
//
// Fonts come from SAFE_FONTS: nothing is embedded in a .pptx, so a font the machine lacks is a
// design that silently becomes a different one.
//
// Colour roles, so a composition can place text without guessing:
//   paper/ink/soft/muted  the page and its three text weights
//   accent/accentInk      the brand colour, and what is legible ON it
//   deep/deepInk/deepSoft the full-bleed field a cover or section is built on

import type { DeckDesign } from "./deck-compose";

export const SAFE_FONTS = [
  "Arial",
  "Calibri",
  "Cambria",
  "Candara",
  "Consolas",
  "Constantia",
  "Corbel",
  "Courier New",
  "Georgia",
  "Tahoma",
  "Times New Roman",
  "Trebuchet MS",
  "Verdana",
] as const;

/** The house design, and the fallback whenever a stored id no longer exists. */
const HOUSE: DeckDesign = {
  accent: "c8102e",
  accentInk: "fff5f5",
  blurb: "Crimson block down the edge, points set as cards. The house look.",
  body: "cards",
  chrome: "full",
  cover: "band-left",
  deep: "17151a",
  deepInk: "f7f4f4",
  deepSoft: "a49ea6",
  exhibit: "ruled",
  fonts: { body: "Calibri", display: "Georgia" },
  id: "studio",
  ink: "17151a",
  mark: "bar",
  motion: "rise",
  muted: "8b8590",
  name: "Studio",
  page: "tab",
  paper: "faf8f7",
  plot: "column",
  quote: "mark",
  second: "ecb7bf",
  section: "band",
  soft: "494650",
  stat: "panel",
};

export const DECK_DESIGNS: readonly DeckDesign[] = [
  HOUSE,
  {
    accent: "8a5a2b",
    accentInk: "fdf8f1",
    blurb: "Handmade paper inside a thin rule. Warm, made by hand, quiet about it.",
    body: "hanging-rule",
    chrome: "light",
    cover: "frame",
    deep: "2b2018",
    deepInk: "f9f2e8",
    deepSoft: "c3b39d",
    exhibit: "open",
    fonts: { body: "Candara", display: "Constantia" },
    id: "atelier",
    ink: "2b2117",
    mark: "diamond",
    motion: "fade",
    muted: "8b7c69",
    name: "Atelier",
    page: "frame",
    paper: "faf5ec",
    plot: "lollipop",
    quote: "rule",
    second: "d9c3a5",
    section: "rule",
    soft: "4c4133",
    stat: "rule",
    texture: { cover: "/deck/textures/paper.jpg", dark: false, scrim: 0, section: "/deck/textures/kraft.jpg" },
  },
  {
    accent: "4a6373",
    accentInk: "f4f7f9",
    blurb: "Slate and concrete. Architectural, heavy, and entirely unfussed.",
    body: "boxed",
    chrome: "full",
    cover: "editorial",
    deep: "12171b",
    deepInk: "f4f6f7",
    deepSoft: "a8b3ba",
    exhibit: "framed",
    fonts: { body: "Corbel", display: "Cambria" },
    id: "quarry",
    ink: "12171b",
    mark: "square",
    motion: "wipe",
    muted: "7c858c",
    name: "Quarry",
    page: "edge",
    paper: "f2f3f4",
    plot: "block",
    quote: "rule",
    second: "ccd6dd",
    section: "band",
    soft: "3c454b",
    stat: "rule",
    texture: { cover: "/deck/textures/slate.jpg", dark: true, scrim: 34, section: "/deck/textures/concrete.jpg" },
  },
  {
    accent: "a2734b",
    accentInk: "fff9f2",
    blurb: "A photograph, a wash of ink across the foot of it, and one line of type.",
    body: "plain",
    chrome: "light",
    cover: "photo",
    deep: "241c16",
    deepInk: "faf4ec",
    deepSoft: "c6b6a5",
    exhibit: "card",
    fonts: { body: "Calibri", display: "Georgia" },
    id: "atrium",
    ink: "2a2119",
    mark: "ring",
    motion: "fade",
    muted: "8b7c6c",
    name: "Atrium",
    page: "clean",
    paper: "fdf9f4",
    plot: "track",
    quote: "mark",
    second: "e2cdb5",
    section: "rule",
    soft: "4a4034",
    stat: "rule",
    texture: { cover: "/deck/textures/photo-desk.jpg", dark: true, scrim: 52, section: "/deck/textures/photo-lecture.jpg" },
  },
  {
    accent: "8c78f0",
    accentInk: "f7f5ff",
    blurb: "Indigo light bleeding into violet. Modern, cinematic, a little loud.",
    body: "cards",
    chrome: "full",
    cover: "editorial",
    deep: "17133a",
    deepInk: "f5f3ff",
    deepSoft: "b3accd",
    exhibit: "tinted",
    fonts: { body: "Corbel", display: "Cambria" },
    id: "nocturne",
    ink: "1b1636",
    mark: "disc",
    motion: "zoom",
    muted: "817ba0",
    name: "Nocturne",
    page: "corner",
    paper: "f8f7fe",
    plot: "outline",
    quote: "band",
    second: "d9d3fb",
    section: "band",
    soft: "413c66",
    stat: "circle",
    texture: { cover: "/deck/textures/field-indigo.jpg", dark: true, scrim: 22, section: "/deck/textures/field-teal.jpg" },
  },
  {
    accent: "2f5fd0",
    accentInk: "f4f7ff",
    blurb: "A navy panel holds the subtitle; points arrive numbered, one rule apart.",
    body: "numbered",
    chrome: "full",
    cover: "panel-right",
    deep: "0d1b33",
    deepInk: "f2f6fc",
    deepSoft: "9db0cd",
    exhibit: "framed",
    fonts: { body: "Calibri", display: "Cambria" },
    id: "meridian",
    ink: "111a2b",
    mark: "chevron",
    motion: "rise",
    muted: "7c8698",
    name: "Meridian",
    page: "margin",
    paper: "ffffff",
    plot: "track",
    quote: "rule",
    second: "c5d2f2",
    section: "split",
    soft: "3d4759",
    stat: "rule",
  },
  {
    accent: "c1121f",
    accentInk: "fff4f2",
    blurb: "Newspaper: a ribbon across the cover, headline banners, hard black rules.",
    body: "banner",
    chrome: "full",
    cover: "ribbon",
    deep: "141414",
    deepInk: "fbfaf8",
    deepSoft: "a8a49e",
    exhibit: "ruled",
    fonts: { body: "Arial", display: "Georgia" },
    id: "bulletin",
    ink: "141414",
    mark: "arrow",
    motion: "wipe",
    muted: "7d7a75",
    name: "Bulletin",
    page: "foot",
    paper: "fbfaf6",
    plot: "block",
    quote: "band",
    second: "ebb9ba",
    section: "band",
    soft: "3f3d3a",
    stat: "block",
  },
  {
    accent: "b3401f",
    accentInk: "fdf6f1",
    blurb: "A thin frame, centred type and a lot of air. Quiet, editorial, printed.",
    body: "boxed",
    chrome: "light",
    cover: "frame",
    deep: "241f1b",
    deepInk: "f7f2ec",
    deepSoft: "b3aaa0",
    exhibit: "open",
    fonts: { body: "Corbel", display: "Constantia" },
    id: "kyoto",
    ink: "231f1c",
    mark: "slash",
    motion: "fade",
    muted: "8a8178",
    name: "Kyoto",
    page: "clean",
    paper: "f7f4ee",
    plot: "lollipop",
    quote: "rule",
    second: "e4c2b4",
    section: "rule",
    soft: "4a443d",
    stat: "rule",
  },
  {
    accent: "c79a2e",
    accentInk: "1d2318",
    blurb: "A giant numeral behind the title, and body copy that hangs off a full rule.",
    body: "hanging-rule",
    chrome: "full",
    cover: "numeral",
    deep: "12241a",
    deepInk: "f2f7f2",
    deepSoft: "a3b7a6",
    exhibit: "ruled",
    fonts: { body: "Corbel", display: "Cambria" },
    id: "atlas",
    ink: "14261c",
    mark: "bar",
    motion: "rise",
    muted: "7f8a80",
    name: "Atlas",
    page: "rail",
    paper: "f6f8f5",
    plot: "column",
    quote: "rule",
    second: "e9debd",
    section: "solid-numeral",
    soft: "3c4a41",
    stat: "rule",
  },
  {
    accent: "0b63e5",
    accentInk: "f2f7ff",
    blurb: "Two blocks in opposite corners; every point becomes a pill you can scan.",
    body: "chips",
    chrome: "full",
    cover: "corner-blocks",
    deep: "0a1929",
    deepInk: "f3f7fb",
    deepSoft: "9cb0c4",
    exhibit: "card",
    fonts: { body: "Tahoma", display: "Trebuchet MS" },
    id: "signal",
    ink: "10171f",
    mark: "plus",
    motion: "zoom",
    muted: "78828d",
    name: "Signal",
    page: "corner",
    paper: "ffffff",
    plot: "outline",
    quote: "panel",
    second: "bbd3f8",
    section: "band",
    soft: "3a434e",
    stat: "circle",
  },
  {
    accent: "d2570d",
    accentInk: "1c1310",
    blurb: "A burning arc in the corner, cards for the content, a slab beside the number.",
    body: "cards",
    chrome: "full",
    cover: "arc-corner",
    deep: "17120f",
    deepInk: "f8f3ee",
    deepSoft: "aca093",
    exhibit: "tinted",
    fonts: { body: "Calibri", display: "Georgia" },
    id: "ember",
    ink: "1d1a17",
    mark: "disc",
    motion: "rise",
    muted: "857d74",
    name: "Ember",
    page: "tint",
    paper: "fbf8f4",
    plot: "track",
    quote: "mark",
    second: "f0cbb3",
    section: "band",
    soft: "46403a",
    stat: "block",
  },
  {
    accent: "e02020",
    accentInk: "ffffff",
    blurb: "Three bars, primary colour, numbered rows. Bauhaus with the volume up.",
    body: "numbered",
    chrome: "full",
    cover: "stack-bars",
    deep: "111111",
    deepInk: "ffffff",
    deepSoft: "a8a8a8",
    exhibit: "framed",
    fonts: { body: "Arial", display: "Arial" },
    id: "primary",
    ink: "111111",
    mark: "square",
    motion: "wipe",
    muted: "767676",
    name: "Primary",
    page: "tab",
    paper: "ffffff",
    plot: "block",
    quote: "panel",
    second: "f6c1c1",
    section: "split",
    soft: "343434",
    stat: "block",
  },
  {
    accent: "9a6b3f",
    accentInk: "fdf9f1",
    blurb: "Centred title between hairlines, indented copy. Reads like a printed essay.",
    body: "hanging-rule",
    chrome: "light",
    cover: "editorial",
    deep: "241c12",
    deepInk: "f8f2e6",
    deepSoft: "bcae97",
    exhibit: "open",
    fonts: { body: "Candara", display: "Georgia" },
    id: "linen",
    ink: "2c2318",
    mark: "slash",
    motion: "fade",
    muted: "8b7f6c",
    name: "Linen",
    page: "margin",
    paper: "faf6ee",
    plot: "lollipop",
    quote: "rule",
    second: "dfcfbd",
    section: "rule",
    soft: "4a4032",
    stat: "rule",
  },
  {
    accent: "1a4fd6",
    accentInk: "f4f7ff",
    blurb: "Half the cover is colour; content sits in two columns either side of a rule.",
    body: "two-col-rule",
    chrome: "full",
    cover: "half-split",
    deep: "0e1f4d",
    deepInk: "f3f6fd",
    deepSoft: "a3b2d4",
    exhibit: "ruled",
    fonts: { body: "Calibri", display: "Cambria" },
    id: "cobalt",
    ink: "0f1729",
    mark: "chevron",
    motion: "rise",
    muted: "79839a",
    name: "Cobalt",
    page: "edge",
    paper: "ffffff",
    plot: "column",
    quote: "band",
    second: "bfcef4",
    section: "band",
    soft: "39435a",
    stat: "panel",
  },
  {
    accent: "c07a17",
    accentInk: "1a1815",
    blurb: "A dotted field, a dark rail beside every list. Industrial and calm.",
    body: "rail",
    chrome: "full",
    cover: "grid-dots",
    deep: "1c1a17",
    deepInk: "f5f3ef",
    deepSoft: "a8a29a",
    exhibit: "framed",
    fonts: { body: "Corbel", display: "Cambria" },
    id: "slate",
    ink: "1c1a17",
    mark: "target",
    motion: "rise",
    muted: "857f77",
    name: "Slate",
    page: "dots",
    paper: "f5f4f2",
    plot: "track",
    quote: "rule",
    second: "e6d2b5",
    section: "split",
    soft: "46423c",
    stat: "rule",
  },
  {
    accent: "b2477a",
    accentInk: "fff5fa",
    blurb: "A rising circle, cards in plum, a ring around every number.",
    body: "cards",
    chrome: "full",
    cover: "circle",
    deep: "22132a",
    deepInk: "f9f2f7",
    deepSoft: "b8a3b8",
    exhibit: "card",
    fonts: { body: "Calibri", display: "Cambria" },
    id: "orchid",
    ink: "241428",
    mark: "ring",
    motion: "zoom",
    muted: "8a7c88",
    name: "Orchid",
    page: "tint",
    paper: "fdf7fa",
    plot: "outline",
    quote: "mark",
    second: "e8c6d6",
    section: "solid-numeral",
    soft: "483f4c",
    stat: "circle",
  },
  {
    accent: "9fe870",
    accentInk: "0c1108",
    blurb: "Black field, a lime band under the title, everything inside a hairline box.",
    body: "boxed",
    chrome: "full",
    cover: "band-bottom",
    deep: "0b0d0c",
    deepInk: "f4f7f4",
    deepSoft: "97a094",
    exhibit: "ruled",
    fonts: { body: "Consolas", display: "Consolas" },
    id: "terminal",
    ink: "10120f",
    mark: "bracket",
    motion: "wipe",
    muted: "7f857c",
    name: "Terminal",
    page: "rail",
    paper: "f4f6f3",
    plot: "column",
    quote: "rule",
    second: "dcf2ce",
    section: "rule",
    soft: "3a3e38",
    stat: "block",
  },
  {
    accent: "0f7d86",
    accentInk: "f0fafb",
    blurb: "A diagonal cut across the cover; titles ride a dark panel above the content.",
    body: "panel-title",
    chrome: "full",
    cover: "split-diagonal",
    deep: "07202e",
    deepInk: "eff8f9",
    deepSoft: "9ab6bd",
    exhibit: "framed",
    fonts: { body: "Corbel", display: "Georgia" },
    id: "harbor",
    ink: "07242c",
    mark: "step",
    motion: "rise",
    muted: "738288",
    name: "Harbor",
    page: "foot",
    paper: "f3f9fa",
    plot: "block",
    quote: "band",
    second: "b3d6da",
    section: "band",
    soft: "35474c",
    stat: "panel",
  },
  {
    accent: "b4562a",
    accentInk: "fdf6ef",
    blurb: "Sandstone block, sienna rules, copy indented off a long line.",
    body: "hanging-rule",
    chrome: "full",
    cover: "band-left",
    deep: "241a12",
    deepInk: "f9f2e8",
    deepSoft: "bfae98",
    exhibit: "tinted",
    fonts: { body: "Tahoma", display: "Constantia" },
    id: "sandstone",
    ink: "2a2119",
    mark: "diamond",
    motion: "fade",
    muted: "8b7f6f",
    name: "Sandstone",
    page: "clean",
    paper: "f8f2e8",
    plot: "lollipop",
    quote: "mark",
    second: "e5c6b3",
    section: "rule",
    soft: "4c4237",
    stat: "rule",
  },
  {
    accent: "6a5ae0",
    accentInk: "f6f4ff",
    blurb: "The one that glows: painted light on the cover, violet cards inside.",
    art: {
      closing: {
        base: "15112e",
        glows: [{ color: "6a5ae0", cx: 0.5, cy: 1.06, r: 0.8, strength: 0.45 }],
        grain: 0.4,
        vignette: 0.42,
      },
      cover: {
        base: "15112e",
        glows: [
          { color: "3b2fa0", cx: 0.16, cy: 0.2, r: 0.6, strength: 0.55 },
          { color: "8c6ce8", cx: 0.88, cy: 0.85, r: 0.58, strength: 0.5 },
        ],
        grain: 0.45,
        vignette: 0.36,
      },
      section: {
        base: "f1eefb",
        glows: [{ color: "ffffff", cx: 0.2, cy: 0.18, r: 0.6, strength: 0.6 }],
        grain: 0.28,
        ramp: { angle: 118, to: "ded7f4" },
      },
    },
    body: "cards",
    chrome: "none",
    cover: "art-glow",
    exhibit: "tinted",
    deep: "15112e",
    deepInk: "f4f1fd",
    deepSoft: "aca4cd",
    fonts: { body: "Corbel", display: "Cambria" },
    id: "aurora",
    ink: "1b1633",
    mark: "disc",
    motion: "zoom",
    muted: "817a9a",
    name: "Aurora",
    page: "clean",
    paper: "f8f6fd",
    plot: "outline",
    quote: "panel",
    second: "d0caf5",
    section: "art",
    soft: "413c5c",
    stat: "circle",
  },
  {
    accent: "d90429",
    accentInk: "ffffff",
    blurb: "Broadsheet: serif headlines, two columns, one red rule doing all the shouting.",
    body: "two-col-rule",
    chrome: "full",
    cover: "ribbon",
    deep: "1a1a1a",
    deepInk: "fafafa",
    deepSoft: "a5a5a5",
    exhibit: "ruled",
    fonts: { body: "Arial", display: "Times New Roman" },
    id: "press",
    ink: "16161a",
    mark: "bracket",
    motion: "fade",
    muted: "76767c",
    name: "Press",
    page: "margin",
    paper: "fdfdfb",
    plot: "column",
    quote: "rule",
    second: "f3b7c0",
    section: "band",
    soft: "3a3a40",
    stat: "rule",
  },
  {
    accent: "2f7d52",
    accentInk: "f3faf5",
    blurb: "A field of green dots, points as chips, a ring around the headline number.",
    body: "chips",
    chrome: "full",
    cover: "grid-dots",
    deep: "0d2119",
    deepInk: "f0f7f2",
    deepSoft: "a2bbaa",
    exhibit: "tinted",
    fonts: { body: "Calibri", display: "Georgia" },
    id: "fern",
    ink: "10261a",
    mark: "plus",
    motion: "rise",
    muted: "7b8a80",
    name: "Fern",
    page: "dots",
    paper: "f4f8f4",
    plot: "track",
    quote: "rule",
    second: "bdd6c7",
    section: "split",
    soft: "39473d",
    stat: "circle",
  },
  {
    accent: "c2600f",
    accentInk: "fff8ef",
    blurb: "A light cover for once: gold band along the bottom, brown ink above it.",
    body: "plain",
    chrome: "light",
    cover: "band-bottom",
    deep: "f3c98a",
    deepInk: "2b2115",
    deepSoft: "6a5334",
    exhibit: "open",
    fonts: { body: "Calibri", display: "Georgia" },
    id: "dawn",
    ink: "2b2115",
    mark: "ring",
    motion: "fade",
    muted: "8a7a63",
    name: "Dawn",
    page: "tint",
    paper: "fffaf2",
    plot: "lollipop",
    quote: "mark",
    second: "eecfb2",
    section: "band",
    soft: "4e4335",
    stat: "rule",
  },
  {
    accent: "e8e8e8",
    accentInk: "111111",
    blurb: "Pure black and white. A numeral, a rail, and nothing it does not need.",
    body: "rail",
    chrome: "full",
    cover: "numeral",
    deep: "000000",
    deepInk: "ffffff",
    deepSoft: "9e9e9e",
    exhibit: "card",
    fonts: { body: "Trebuchet MS", display: "Trebuchet MS" },
    id: "onyx",
    ink: "000000",
    mark: "step",
    motion: "wipe",
    muted: "757575",
    name: "Onyx",
    page: "rail",
    paper: "ffffff",
    plot: "block",
    quote: "band",
    second: "f9f9f9",
    section: "solid-numeral",
    soft: "2e2e2e",
    stat: "block",
  },
  // ── the Keynote categories the set was still missing (owner 2026-08-24: fill every one) ────
  //
  // Education, Portfolio, Craft, Textured, Personal and a true Minimal. Each is built on the
  // same rule as the rest: a cover construction plus a way of setting a list that no other
  // design in the set uses — and now an interior grid, an exhibit dressing and a plot style
  // as well, because "it looks the same after the title slide" was the verdict on a set that
  // only varied its covers.
  {
    accent: "2f6f4e",
    accentInk: "f2f8f2",
    blurb: "Chalk green on cream, points numbered. Reads like a good lecture handout.",
    body: "numbered",
    chrome: "full",
    cover: "half-split",
    deep: "1b2b22",
    deepInk: "f4f1e6",
    deepSoft: "b3bdb2",
    exhibit: "ruled",
    fonts: { body: "Trebuchet MS", display: "Constantia" },
    id: "schoolhouse",
    ink: "1f2a24",
    mark: "plus",
    motion: "rise",
    muted: "8a938c",
    name: "Schoolhouse",
    page: "tab",
    paper: "fbf7ee",
    plot: "column",
    quote: "rule",
    second: "b7d3c1",
    section: "band",
    soft: "45514a",
    stat: "rule",
    texture: { dark: true, scrim: 30, section: "/deck/textures/chalkboard.jpg" },
  },
  {
    accent: "1f5f8b",
    accentInk: "eef6fb",
    blurb: "Engineering graph paper, inside and out. Navy rule, quiet margin.",
    body: "plain",
    chrome: "full",
    cover: "frame",
    deep: "15212c",
    deepInk: "eef3f7",
    deepSoft: "9fb0bd",
    exhibit: "open",
    fonts: { body: "Calibri", display: "Cambria" },
    id: "notebook",
    ink: "1c2733",
    mark: "square",
    motion: "fade",
    muted: "8492a0",
    name: "Notebook",
    page: "margin",
    paper: "f7f8f6",
    plot: "track",
    quote: "rule",
    second: "b7d2e6",
    section: "rule",
    soft: "41505f",
    stat: "rule",
    texture: { cover: "/deck/textures/graph-paper.jpg", dark: false, page: "/deck/textures/graph-paper.jpg", pageScrim: 48, scrim: 34 },
  },
  {
    accent: "9a7b4f",
    accentInk: "fdfaf5",
    blurb: "A photograph, a bronze rule and nothing else. Built to show work.",
    body: "hanging-rule",
    chrome: "light",
    cover: "photo",
    deep: "121212",
    deepInk: "f7f7f7",
    deepSoft: "b0b0b0",
    exhibit: "open",
    fonts: { body: "Corbel", display: "Georgia" },
    id: "gallery",
    ink: "141414",
    mark: "slash",
    motion: "fade",
    muted: "8c8c8c",
    name: "Gallery",
    page: "clean",
    paper: "fcfcfc",
    plot: "column",
    quote: "rule",
    second: "d8cdba",
    section: "rule",
    soft: "4a4a4a",
    stat: "rule",
    texture: { cover: "/deck/textures/photo-gallery.jpg", dark: true, section: "/deck/textures/photo-gallery.jpg", scrim: 55 },
  },
  {
    accent: "9c5a2c",
    accentInk: "fdf5ee",
    blurb: "A workbench under the title, warm cards below it. Things made by hand.",
    body: "cards",
    chrome: "full",
    cover: "frame",
    deep: "241c15",
    deepInk: "f6efe6",
    deepSoft: "bfae9b",
    exhibit: "card",
    fonts: { body: "Candara", display: "Constantia" },
    id: "bench",
    ink: "2a211a",
    mark: "bracket",
    motion: "rise",
    muted: "8d7f70",
    name: "Bench",
    page: "tint",
    paper: "faf6f0",
    plot: "outline",
    quote: "panel",
    second: "e0c3a4",
    section: "band",
    soft: "4f4237",
    stat: "panel",
    texture: { cover: "/deck/textures/photo-bench.jpg", dark: true, scrim: 58 },
  },
  {
    accent: "7d3b3b",
    accentInk: "fbf2f0",
    blurb: "Dark board, oxblood rule, numbered inside. A bound report.",
    body: "numbered",
    chrome: "light",
    cover: "editorial",
    deep: "231d16",
    deepInk: "f3ece1",
    deepSoft: "b9ac99",
    exhibit: "ruled",
    fonts: { body: "Corbel", display: "Constantia" },
    id: "bindery",
    ink: "2b241c",
    mark: "diamond",
    motion: "fade",
    muted: "8d8375",
    name: "Bindery",
    page: "rail",
    paper: "f6f1e9",
    plot: "lollipop",
    quote: "rule",
    second: "d9c1a3",
    section: "rule",
    soft: "51483c",
    stat: "rule",
    texture: { closing: "/deck/textures/kraft-dark.jpg", cover: "/deck/textures/kraft-dark.jpg", dark: true, scrim: 28 },
  },
  {
    accent: "46584a",
    accentInk: "f2f6f1",
    blurb: "Raw canvas under every page, sage green over it. Quiet and made of cloth.",
    body: "cards",
    chrome: "full",
    cover: "stack-bars",
    deep: "26251f",
    deepInk: "f4f1e8",
    deepSoft: "b6b1a2",
    exhibit: "tinted",
    fonts: { body: "Candara", display: "Cambria" },
    id: "weave",
    ink: "2c2a24",
    mark: "square",
    motion: "rise",
    muted: "91897a",
    name: "Weave",
    page: "clean",
    paper: "f7f2e9",
    plot: "block",
    quote: "mark",
    second: "bfcdbc",
    section: "rule",
    soft: "524c41",
    stat: "rule",
    texture: { cover: "/deck/textures/canvas-weave.jpg", dark: false, page: "/deck/textures/canvas-weave.jpg", pageScrim: 86, scrim: 62 },
  },
  {
    accent: "d0714a",
    accentInk: "fff6f1",
    blurb: "A chalkboard cover, warm chips inside, a banded foot. Loud in a good way.",
    body: "chips",
    chrome: "full",
    cover: "band-bottom",
    deep: "1a221e",
    deepInk: "f2f5f1",
    deepSoft: "aab5ad",
    exhibit: "framed",
    fonts: { body: "Trebuchet MS", display: "Georgia" },
    id: "chalk",
    ink: "1e2622",
    mark: "plus",
    motion: "wipe",
    muted: "87938c",
    name: "Chalk",
    page: "foot",
    paper: "f4f6f4",
    plot: "column",
    quote: "band",
    second: "f0b79c",
    section: "band",
    soft: "44504a",
    stat: "block",
    texture: { cover: "/deck/textures/chalkboard.jpg", dark: true, scrim: 22 },
  },
  {
    accent: "c9761a",
    accentInk: "fff8ef",
    blurb: "An amber field and a warm tinted page. Personal, and not shy about it.",
    body: "chips",
    chrome: "full",
    cover: "arc-corner",
    deep: "2a1a0e",
    deepInk: "fbf1e3",
    deepSoft: "c8ac8d",
    exhibit: "card",
    fonts: { body: "Corbel", display: "Georgia" },
    id: "marigold",
    ink: "2b2118",
    mark: "ring",
    motion: "zoom",
    muted: "917f6c",
    name: "Marigold",
    page: "tint",
    paper: "fdf8f0",
    plot: "outline",
    quote: "mark",
    second: "f3c893",
    section: "split",
    soft: "544335",
    stat: "circle",
    texture: { closing: "/deck/textures/field-amber.jpg", cover: "/deck/textures/field-amber.jpg", dark: true, scrim: 18 },
  },
  {
    accent: "8e4f77",
    accentInk: "fdf4fa",
    blurb: "Dusk colours, a circle on the cover, a wedge in the corner of every page.",
    body: "plain",
    chrome: "light",
    cover: "circle",
    deep: "201a26",
    deepInk: "f6f0f8",
    deepSoft: "b5abbf",
    exhibit: "tinted",
    fonts: { body: "Calibri", display: "Cambria" },
    id: "dusk",
    ink: "241d26",
    mark: "disc",
    motion: "zoom",
    muted: "8a8093",
    name: "Dusk",
    page: "corner",
    paper: "faf6f8",
    plot: "lollipop",
    quote: "panel",
    second: "ddc0d5",
    section: "band",
    soft: "4b4150",
    stat: "circle",
    texture: { cover: "/deck/textures/field-rose.jpg", dark: true, scrim: 20 },
  },
  {
    accent: "33383d",
    accentInk: "fafafa",
    blurb: "White paper, one grey, no ornament at all. For work that should not be decorated.",
    body: "plain",
    chrome: "light",
    cover: "editorial",
    deep: "141414",
    deepInk: "f5f5f5",
    deepSoft: "a8a8a8",
    exhibit: "open",
    fonts: { body: "Verdana", display: "Georgia" },
    id: "quiet",
    ink: "191919",
    kicker: false,
    mark: "slash",
    motion: "fade",
    muted: "949494",
    name: "Quiet",
    page: "clean",
    paper: "ffffff",
    plot: "column",
    quote: "rule",
    second: "c9ced3",
    section: "rule",
    soft: "4d4d4d",
    stat: "rule",
  },
];

export const DEFAULT_DECK_DESIGN = HOUSE.id;

/** Look one up by id, falling back to the house design — a stored id must never break a build. */
export function deckDesign(id: string | null | undefined): DeckDesign {
  return DECK_DESIGNS.find((d) => d.id === id) ?? HOUSE;
}
